#!/usr/bin/env node
// build-tokens.mjs — generate tokens.css from the DTCG sources in tokens/.
//
// Architecture (the standard three-tier model, minus tier 3):
//   tier 1  tokens/themes/<id>.json  raw palette, one file per theme, each
//                                    emitted as its own [data-theme] block
//   tier 2  tokens/semantic.json     aliases + theme-invariant metrics, :root
//   tier 3  (none yet)               component tokens are deliberately absent;
//                                    nothing varies per-component per-theme yet
//
// Theme-invariant type/space/radius live in packages/tokens/foundation.css,
// which is shared with the docs repo and is NOT generated here — tokens.css
// @imports it via prelude.css.
//
// `outputReferences: true` is load-bearing: the semantic tier must emit
// `var(--pv-ink)` rather than a resolved literal, or every theme would inherit
// Warm Slate's palette instead of overriding it.
//
// Usage: node apps/desktop/scripts/build-tokens.mjs [--check]
//   --check  regenerate into memory and diff against the committed file,
//            exiting 1 on drift (used by CI)

import StyleDictionary from 'style-dictionary';
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, basename, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// Paths resolve from this file, not the cwd: CI invokes it via
// `pnpm --filter @astro-plan/desktop run lint`, which runs from apps/desktop,
// while a developer runs it from the repo root. Both must work.
const APP_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const TOKENS_DIR = join(APP_DIR, 'tokens');
const OUT = join(APP_DIR, 'src/styles/tokens.css');
const PRELUDE = join(TOKENS_DIR, 'prelude.css');

// Warm Slate doubles as the bare `:root` default so the default light palette
// (pre-hydration, vitest, no data-theme) has a single source of truth.
const DEFAULT_THEME = 'warm-slate';

const themeIds = readdirSync(join(TOKENS_DIR, 'themes'))
  .filter((f) => f.endsWith('.json'))
  .map((f) => basename(f, '.json'))
  .sort();

/** Which source file a token came from — used to split the tiers apart. */
const fromFile = (suffix) => (token) => (token.filePath ?? '').endsWith(suffix);

// Uses SD's built-in `css/variables` format rather than a hand-written one.
// A custom format that reads `token.$value` directly bypasses outputReferences
// and emits resolved literals — which flattens the semantic tier to Warm
// Slate's palette, so every other theme silently stops applying.
async function buildBlock({ sources, selector, include }) {
  const sd = new StyleDictionary({
    source: sources,
    platforms: {
      css: {
        transformGroup: 'css',
        prefix: 'pv',
        files: [
          {
            destination: 'block.css',
            format: 'css/variables',
            filter: include,
            options: { selector, outputReferences: true },
          },
        ],
      },
    },
    log: { verbosity: 'silent', warnings: 'disabled' },
  });
  const built = await sd.formatPlatform('css');
  return built[0].output;
}

// The semantic tier references raw palette tokens, so each build must also
// load a theme for those references to resolve — the `include` filter then
// keeps only the tier being emitted.
const semanticSrc = join(TOKENS_DIR, 'semantic.json');
const themeSrc = (id) => join(TOKENS_DIR, 'themes', `${id}.json`);

const blocks = [];

blocks.push(
  await buildBlock({
    sources: [semanticSrc, themeSrc(DEFAULT_THEME)],
    selector: ':root',
    include: fromFile('semantic.json'),
  }),
);

for (const id of themeIds) {
  const selector =
    id === DEFAULT_THEME ? `:root,\n[data-theme="${id}"]` : `[data-theme="${id}"]`;
  blocks.push(
    await buildBlock({
      sources: [semanticSrc, themeSrc(id)],
      selector,
      include: fromFile(`${id}.json`),
    }),
  );
}

const densityIds = readdirSync(join(TOKENS_DIR, 'density'))
  .filter((f) => f.endsWith('.json'))
  .map((f) => basename(f, '.json'))
  .sort();

// Density is a third axis, orthogonal to theme — it overrides row metrics only.
for (const id of densityIds) {
  blocks.push(
    await buildBlock({
      sources: [semanticSrc, themeSrc(DEFAULT_THEME), join(TOKENS_DIR, 'density', `${id}.json`)],
      selector: `.density-${id}`,
      include: fromFile(`density/${id}.json`),
    }),
  );
}

const banner =
  '/* AUTO-GENERATED by scripts/build-tokens.mjs from apps/desktop/tokens/ —\n' +
  '   do not edit by hand. Run `pnpm tokens:build` after editing the DTCG\n' +
  '   sources. CI fails if this file drifts from them. */\n';

const output = `${banner}${readFileSync(PRELUDE, 'utf8')}\n${blocks.join('\n')}`;

if (process.argv.includes('--check')) {
  const current = readFileSync(OUT, 'utf8');
  if (current !== output) {
    console.error(
      `ERROR: ${OUT} is out of date with apps/desktop/tokens/.\n` +
        'Run `pnpm tokens:build` and commit the result.',
    );
    process.exit(1);
  }
  console.log(`OK: ${OUT} matches its DTCG sources (${themeIds.length} themes).`);
} else {
  writeFileSync(OUT, output);
  console.log(`wrote ${OUT} — ${themeIds.length} themes + semantic tier`);
}
