// Copyright (C) 2024-2026 Sjors Robroek
// SPDX-License-Identifier: AGPL-3.0-only

//! Comprehensive permutation-matrix coverage for `detect_master` (issue #514).
//!
//! Mirrors the fixture matrix generated by
//! `docs/development/fixtures/gen_detection_matrix.py` (frame type × raw/master ×
//! header/path/negative), but drives `DetectInput` directly instead of writing
//! FITS files — the detector operates on parsed header/path values, not bytes.
//!
//! Table-driven: one `Case` per permutation cell, with an optional expected
//! `(FrameType, is_master)` (`None` means `detect_master` must return `None`).
//! Naming deliberately keeps "master"/"_stacked" tokens OUT of cases that test
//! header-only evidence (STACKCNT, plain IMAGETYP) so a naming-heuristic bug
//! cannot mask a header-evidence bug, matching the convention already used by
//! `lib.rs`'s registry-ordering tests.

use calibration_master_detect::{detect_master, DetectInput};
use metadata_core::FrameType;

struct Case {
    name: &'static str,
    imagetyp: Option<&'static str>,
    stack_count: Option<u32>,
    file_name: &'static str,
    rel_path: &'static str,
    /// `None` => `detect_master` must return `None`. `Some((type, is_master))`
    /// checks only those two fields; `detector` is asserted separately where
    /// provenance matters.
    expected: Option<(FrameType, bool)>,
}

struct TypeSpec {
    name: &'static str,
    primary: &'static str,
    synonyms: &'static [&'static str],
    pi_label: &'static str,
    lower: &'static str,
}

const TYPES: &[TypeSpec] = &[
    TypeSpec {
        name: "Light",
        primary: "LIGHT",
        synonyms: &["Light Frame", "SCIENCE"],
        pi_label: "Master Light",
        lower: "light",
    },
    TypeSpec {
        name: "Dark",
        primary: "DARK",
        synonyms: &["Dark Frame"],
        pi_label: "Master Dark",
        lower: "dark",
    },
    TypeSpec {
        name: "Flat",
        primary: "FLAT",
        synonyms: &["Flat Field"],
        pi_label: "Master Flat",
        lower: "flat",
    },
    TypeSpec {
        name: "Bias",
        primary: "BIAS",
        synonyms: &["OFFSET", "Bias Frame"],
        pi_label: "Master Bias",
        lower: "bias",
    },
    TypeSpec {
        name: "DarkFlat",
        primary: "DARKFLAT",
        synonyms: &["Dark Flat"],
        pi_label: "Master DarkFlat",
        lower: "darkflat",
    },
];

fn frame_type_of(name: &str) -> FrameType {
    match name {
        "Light" => FrameType::Light,
        "Dark" => FrameType::Dark,
        "Flat" => FrameType::Flat,
        "Bias" => FrameType::Bias,
        "DarkFlat" => FrameType::DarkFlat,
        other => panic!("unknown type spec name: {other}"),
    }
}

/// Pushes the seven per-type-family cells (raw/master × header/path/negative)
/// for one `TypeSpec` onto `cases`. Split out of `build_cases` so each
/// function stays under clippy's `too_many_lines` threshold.
fn push_type_cases(cases: &mut Vec<Case>, t: &TypeSpec) {
    let ft = frame_type_of(t.name);

    // ── raw · header (positive): plain IMAGETYP, no master signal ──────
    cases.push(Case {
        name: leak(format!("{}_raw_header_primary", t.name)),
        imagetyp: Some(t.primary),
        stack_count: None,
        file_name: leak(format!("{}_frame_0001.fits", t.lower)),
        rel_path: leak(format!("Calibration/{}s/", t.name)),
        expected: Some((ft, false)),
    });
    for (i, syn) in t.synonyms.iter().enumerate() {
        cases.push(Case {
            name: leak(format!("{}_raw_header_synonym_{i}", t.name)),
            imagetyp: Some(syn),
            stack_count: None,
            file_name: leak(format!("{}_frame_syn{i}.fits", t.lower)),
            rel_path: leak(format!("Calibration/{}s/", t.name)),
            expected: Some((ft, false)),
        });
    }
    // STACKCNT==1 is decisive evidence of "not stacked" — still raw.
    cases.push(Case {
        name: leak(format!("{}_raw_header_stackcnt_one_not_master", t.name)),
        imagetyp: Some(t.primary),
        stack_count: Some(1),
        file_name: leak(format!("{}_frame_0002.fits", t.lower)),
        rel_path: leak(format!("Calibration/{}s/", t.name)),
        expected: Some((ft, false)),
    });

    // ── raw · name-only (NEGATIVE): no IMAGETYP, type token in name ────
    // Filenames must never classify a raw — this is the #513 regression.
    cases.push(Case {
        name: leak(format!("{}_raw_nameonly_negative", t.name)),
        imagetyp: None,
        stack_count: None,
        file_name: leak(format!("{}_sub_0001.fits", t.lower)),
        rel_path: "Unsorted/",
        expected: None,
    });

    // ── master · header (Siril STACKCNT), name/path carry NO master
    // token so this isolates header evidence from the naming heuristic.
    cases.push(Case {
        name: leak(format!("{}_master_header_stackcnt", t.name)),
        imagetyp: Some(t.primary),
        stack_count: Some(30),
        file_name: leak(format!("{}_0030combined.fits", t.lower)),
        rel_path: leak(format!("Calibration/{}s/Combined30/", t.name)),
        expected: Some((ft, true)),
    });

    // ── master · header (PixInsight "Master X"), incl. lowercase case ──
    cases.push(Case {
        name: leak(format!("{}_master_header_pi", t.name)),
        imagetyp: Some(t.pi_label),
        stack_count: None,
        file_name: leak(format!("master{}.xisf", t.name)),
        rel_path: leak(format!("Calibration/Masters/master{}s/", t.name)),
        expected: Some((ft, true)),
    });
    cases.push(Case {
        name: leak(format!("{}_master_header_pi_lowercase", t.name)),
        imagetyp: Some(leak(t.pi_label.to_ascii_lowercase())),
        stack_count: None,
        file_name: leak(format!("master{}_lc.xisf", t.name)),
        rel_path: leak(format!("Calibration/Masters/master{}s/", t.name)),
        expected: Some((ft, true)),
    });

    // ── master · path fallback (no header at all) ───────────────────────
    // Exercises `infer_frame_type_from_path`: type comes from the path
    // itself only because the path also signals "master".
    cases.push(Case {
        name: leak(format!("{}_master_path_fallback", t.name)),
        imagetyp: None,
        stack_count: None,
        file_name: leak(format!("master{}_A.fits", t.name)),
        rel_path: leak(format!("Calibration/Masters/master{}s/", t.name)),
        expected: Some((ft, true)),
    });
    cases.push(Case {
        name: leak(format!("{}_master_path_stacked_suffix", t.name)),
        imagetyp: None,
        stack_count: None,
        file_name: leak(format!("{}_LUM_stacked.fits", t.lower)),
        rel_path: "Processed/",
        expected: Some((ft, true)),
    });

    // ── master · NEGATIVE: STACKCNT present but no IMAGETYP and no
    // master-signalling path — Siril needs IMAGETYP, PixInsight needs a
    // master-signalling path when IMAGETYP is absent. Must stay None.
    cases.push(Case {
        name: leak(format!("{}_master_negative_stackcnt_no_header_no_path", t.name)),
        imagetyp: None,
        stack_count: Some(30),
        file_name: leak(format!("integration_{}_20250503.fits", t.lower)),
        rel_path: "Unsorted/",
        expected: None,
    });
}

/// Pushes the type-independent cells (header-vs-name conflicts, stacked-light
/// integration, unclassifiable inputs) onto `cases`. Split out of
/// `build_cases` so each function stays under clippy's `too_many_lines`
/// threshold.
fn push_global_cases(cases: &mut Vec<Case>) {
    // ── header-vs-name CONFLICT — header MUST win ──────────────────
    cases.push(Case {
        name: "conflict_header_dark_named_masterflat",
        imagetyp: Some("DARK"),
        stack_count: None,
        file_name: "masterFlat_named_but_header_DARK.fits",
        rel_path: "Conflicts/",
        expected: Some((FrameType::Dark, true)),
    });
    cases.push(Case {
        name: "conflict_header_bias_named_light",
        imagetyp: Some("BIAS"),
        stack_count: None,
        file_name: "light_named_but_header_BIAS.fits",
        rel_path: "Conflicts/",
        expected: Some((FrameType::Bias, false)),
    });
    cases.push(Case {
        name: "conflict_header_flat_stackcnt_named_dark",
        imagetyp: Some("FLAT"),
        stack_count: Some(5),
        file_name: "dark_named_header_FLAT_stackcnt.fit",
        rel_path: "Conflicts/",
        expected: Some((FrameType::Flat, true)),
    });

    // ── master LIGHT (integration) via STACKCNT — a stacked light
    // is a legitimate master-detection outcome, not just calibration frames.
    cases.push(Case {
        name: "master_light_via_stackcnt_integration",
        imagetyp: Some("LIGHT"),
        stack_count: Some(45),
        file_name: "M51_LUM_integration_0001.fits",
        rel_path: "Integrations/",
        expected: Some((FrameType::Light, true)),
    });

    // ── unknown / unclassifiable ────────────────────────────────────
    cases.push(Case {
        name: "unknown_imagetyp_value",
        imagetyp: Some("JUNKTYPE"),
        stack_count: None,
        file_name: "junk_imagetyp.fits",
        rel_path: "Unknown/",
        expected: None,
    });
    cases.push(Case {
        name: "no_header_neutral_name",
        imagetyp: None,
        stack_count: None,
        file_name: "no_header_neutral.fits",
        rel_path: "Unknown/",
        expected: None,
    });
    // Reproduces the exact stripped-header scenario that hid real masters
    // from the scan preview in #513: no IMAGETYP, and the name/path carry no
    // "master"/"_stacked" token (only free-text digits), so it must stay
    // unclassifiable rather than being guessed from the file name.
    cases.push(Case {
        name: "stripped_header_reproduces_513",
        imagetyp: None,
        stack_count: None,
        file_name: "dark_exp_120_stack_9_stripped.fits",
        rel_path: "Unknown/",
        expected: None,
    });
}

fn build_cases() -> Vec<Case> {
    let mut cases = Vec::new();

    for t in TYPES {
        push_type_cases(&mut cases, t);
    }
    push_global_cases(&mut cases);

    cases
}

/// Leak a `String` to a `'static str` so generated case fields can share the
/// `Case` struct's borrowed-str shape used by hand-written cases. Test-only;
/// the leaked memory is reclaimed when the test process exits.
fn leak(s: impl Into<String>) -> &'static str {
    Box::leak(s.into().into_boxed_str())
}

#[test]
fn detect_master_permutation_matrix() {
    let cases = build_cases();
    assert!(cases.len() >= 55, "expected a comprehensive matrix, got {} cases", cases.len());

    let mut failures = Vec::new();
    for case in &cases {
        let input = DetectInput {
            imagetyp: case.imagetyp,
            stack_count: case.stack_count,
            file_name: case.file_name,
            rel_path: case.rel_path,
        };
        let actual = detect_master(&input);
        let actual_summary = actual.as_ref().map(|d| (d.frame_type, d.is_master));
        if actual_summary != case.expected {
            failures.push(format!(
                "{}: expected {:?}, got {:?} (full: {:?})",
                case.name, case.expected, actual_summary, actual
            ));
        }
    }

    assert!(failures.is_empty(), "permutation matrix mismatches:\n{}", failures.join("\n"));
}

/// Provenance check for a sample of cells where the winning detector matters:
/// STACKCNT evidence must come from Siril; a no-header path-fallback master
/// can only come from `PixInsight` (Siril requires IMAGETYP).
#[test]
fn detect_master_permutation_matrix_provenance_sample() {
    let stackcnt_case = DetectInput {
        imagetyp: Some("DARK"),
        stack_count: Some(30),
        file_name: "dark_0030combined.fits",
        rel_path: "Calibration/Darks/Combined30/",
    };
    let result = detect_master(&stackcnt_case).unwrap();
    assert_eq!(result.detector, "siril");
    assert!(result.stack_count_evidence);

    let path_fallback_case = DetectInput {
        imagetyp: None,
        stack_count: None,
        file_name: "masterFlat_A.fits",
        rel_path: "Calibration/Masters/masterFlats/",
    };
    let result = detect_master(&path_fallback_case).unwrap();
    assert_eq!(result.detector, "pixinsight");
    assert!(!result.stack_count_evidence);
}
