/**
 * Canonical alias module (T117 — CB4).
 *
 * Every `_Serialize` / `_Deserialize` → clean-name re-export lives HERE and
 * only here. Consumers import the clean name from this module; they MUST NOT
 * create ad-hoc `X_Serialize as X` aliases in local import blocks.
 *
 * Do NOT hand-edit `bindings/index.ts` (generated by tauri-specta). Add new
 * aliases below as new Rust types are added.
 */

export type {
  // ── Inbox (spec 041) ──────────────────────────────────────────────────────
  InboxClassifyResponse_Serialize as InboxClassifyResponse,
  InboxConfirmRequest_Deserialize as InboxConfirmRequest,
  InboxReclassifyResponse_Serialize as InboxReclassifyResponse,

  // ── Calibration masters (spec 040) ────────────────────────────────────────
  CalibrationMaster_Serialize as CalibrationMaster,
  MasterDetail_Serialize as MasterDetail,

  // ── Targets gen-3 (spec 036) ──────────────────────────────────────────────
  TargetDetailV3_Deserialize as TargetDetailV3,
  TargetOpError_Serialize as TargetOpError,

  // ── SIMBAD resolution (spec 035) ──────────────────────────────────────────
  TargetSearchRequest_Serialize as TargetSearchRequest,
  TargetSearchResponse_Deserialize as TargetSearchResponse,
  TargetSuggestion_Deserialize as TargetSuggestion,
  TargetResolveSimbadRequest_Serialize as TargetResolveSimbadRequest,
  TargetResolveSimbadResponse_Deserialize as TargetResolveSimbadResponse,
  ResolvedTarget_Deserialize as ResolvedTarget,

  // ── Manifests (spec 026 / 008) ─────────────────────────────────────────────
  ManifestListRequest_Deserialize as ManifestListRequest,
  ManifestListResponse_Serialize as ManifestListResponse,
  ManifestGetResponse_Serialize as ManifestGetResponse,
  ManifestOpError_Serialize as ManifestOpError,
} from './index';
