// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  `provenance.read` Tauri command — returns the contract response shape.
	 * 
	 *  # Errors
	 *  Never returns `Err`; persistence failures are folded into
	 *  `ProvenanceReadResponse::error(...)`. The `Result` shape exists so the
	 *  frontend's invoke wrapper still gets a typed envelope.
	 */
	provenanceRead: (request: ProvenanceReadRequest_Deserialize) => typedError<ProvenanceReadResponse_Serialize, string>(__TAURI_INVOKE("provenance_read", { request })),
	/**
	 *  `lifecycle.transition.apply` Tauri command.
	 * 
	 *  # Errors
	 *  Never returns `Err`; refusal / persistence errors fold into
	 *  `TransitionResponse::error(...)` per the contract.
	 */
	lifecycleTransitionApply: (request: TransitionRequest_Deserialize) => typedError<TransitionResponse_Serialize, string>(__TAURI_INVOKE("lifecycle_transition_apply", { request })),
	/**
	 *  `lifecycle.transition.preview` — read-only dry-run for UI button enabling.
	 * 
	 *  # Errors
	 *  Never returns `Err`; refusal codes fold into `TransitionResponse::error(...)`.
	 */
	lifecycleTransitionPreview: (request: TransitionRequest_Deserialize) => typedError<TransitionResponse_Serialize, string>(__TAURI_INVOKE("lifecycle_transition_preview", { request })),
	/**
	 *  `lifecycle.ledger.list` Tauri command.
	 * 
	 *  # Errors
	 *  Returns a stringified persistence error when the repository query fails
	 *  (e.g. transient DB unavailability). Successful empty results are `Ok(vec![])`.
	 */
	lifecycleLedgerList: (filter: LedgerFilterDto) => typedError<LedgerRowDto[], string>(__TAURI_INVOKE("lifecycle_ledger_list", { filter })),
	/**
	 *  `sessions.list` — returns all acquisition sessions.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	sessionsList: () => typedError<AcquisitionSession_Serialize[], string>(__TAURI_INVOKE("sessions.list")),
	/**
	 *  `sessions.get` — returns a single session detail.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	sessionsGet: (id: string) => typedError<SessionDetail_Serialize, string>(__TAURI_INVOKE("sessions.get", { id })),
	/**
	 *  `sessions.calendar` — returns calendar data for a month range.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	sessionsCalendar: (startMonth: string, endMonth: string) => typedError<CalendarData, string>(__TAURI_INVOKE("sessions.calendar", { startMonth, endMonth })),
	/**
	 *  `sessions.transition` — transition a session to a new state.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	sessionsTransition: (id: string, action: string, metadata: unknown | null) => typedError<AcquisitionSession_Serialize, string>(__TAURI_INVOKE("sessions.transition", { id, action, metadata })),
	/**
	 *  `sessions.split` — split a session at a given frame index.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	sessionsSplit: (id: string, splitAtIndex: number) => typedError<SessionSplitResult_Serialize, string>(__TAURI_INVOKE("sessions.split", { id, splitAtIndex })),
	/**
	 *  `sessions.merge` — merge multiple sessions into one.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	sessionsMerge: (ids: string[]) => typedError<AcquisitionSession_Serialize, string>(__TAURI_INVOKE("sessions.merge", { ids })),
	/**
	 *  `calibration.masters.list` — returns all calibration masters.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	calibrationMastersList: () => typedError<CalibrationMaster_Serialize[], string>(__TAURI_INVOKE("calibration.masters.list")),
	/**
	 *  `calibration.masters.get` — returns a single calibration master detail.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	calibrationMastersGet: (id: string) => typedError<MasterDetail_Serialize, string>(__TAURI_INVOKE("calibration.masters.get", { id })),
	/**
	 *  `calibration.matches` — returns calibration match candidates for a session.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	calibrationMatches: (sessionId: string) => typedError<MatchCandidate_Serialize[], string>(__TAURI_INVOKE("calibration.matches", { sessionId })),
	/**
	 *  `targets.list` — returns all targets, optionally filtered by search.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	targetsList: (search: string | null) => typedError<Target_Serialize[], string>(__TAURI_INVOKE("targets.list", { search })),
	/**
	 *  `targets.get` — returns a single target detail.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	targetsGet: (id: string) => typedError<TargetDetail_Serialize, string>(__TAURI_INVOKE("targets.get", { id })),
	/**
	 *  `projects.list` — returns all projects.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	projectsList: (filters: unknown | null) => typedError<Project_Serialize[], string>(__TAURI_INVOKE("projects.list", { filters })),
	/**
	 *  `projects.get` — returns a single project detail.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	projectsGet: (id: string) => typedError<ProjectDetail_Serialize, string>(__TAURI_INVOKE("projects.get", { id })),
	/**
	 *  `projects.create_plan` — create a filesystem plan from wizard state.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	projectsCreatePlan: (wizardState: unknown) => typedError<FilesystemPlan_Serialize, string>(__TAURI_INVOKE("projects.create_plan", { wizardState })),
	/**
	 *  `plans.list` — returns all filesystem plans.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	plansList: (filters: unknown | null) => typedError<FilesystemPlan_Serialize[], string>(__TAURI_INVOKE("plans.list", { filters })),
	/**
	 *  `plans.get` — returns a single plan detail.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	plansGet: (id: string) => typedError<PlanDetail_Serialize, string>(__TAURI_INVOKE("plans.get", { id })),
	/**
	 *  `plans.approve` — approve a plan for application.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	plansApprove: (id: string, deleteAcknowledged: boolean | null) => typedError<FilesystemPlan_Serialize, string>(__TAURI_INVOKE("plans.approve", { id, deleteAcknowledged })),
	/**
	 *  `plans.apply` — apply an approved plan, returning an operation handle.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	plansApply: (id: string) => typedError<IpcOperationHandle, string>(__TAURI_INVOKE("plans.apply", { id })),
	/**
	 *  `plans.discard` — discard a plan.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	plansDiscard: (id: string) => typedError<null, string>(__TAURI_INVOKE("plans.discard", { id })),
	/**
	 *  `audit.list` — returns paginated audit entries.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	auditList: (filters: unknown | null, pagination: unknown | null) => typedError<AuditListResponse_Serialize, string>(__TAURI_INVOKE("audit.list", { filters, pagination })),
	/**
	 *  `audit.export` — export audit entries as newline-delimited JSON.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	auditExport: (filters: unknown | null) => typedError<string, string>(__TAURI_INVOKE("audit.export", { filters })),
	/**
	 *  `review.queue` — returns items awaiting user review.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	reviewQueue: (filter: string | null) => typedError<ReviewItem_Serialize[], string>(__TAURI_INVOKE("review.queue", { filter })),
	/**
	 *  `roots.list` — returns all registered library roots.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	rootsList: () => typedError<LibraryRoot_Serialize[], string>(__TAURI_INVOKE("roots.list")),
	/**
	 *  `roots.register` — register a new library root.
	 * 
	 *  Delegates to `app_core::first_run::register_source` for path validation,
	 *  duplicate detection, and persistence. The `scan_settings` parameter is
	 *  reserved for future scan configuration; currently only `scanDepth` is
	 *  extracted.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on path validation failure, duplicate, or DB error.
	 */
	rootsRegister: (path: string, category: string, scanSettings: unknown) => typedError<RegisterSourceResponse, string>(__TAURI_INVOKE("roots.register", { path, category, scanSettings })),
	/**
	 *  `roots.register.batch` — register multiple source directories at once.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on catastrophic failure; per-item errors are in the response.
	 */
	rootsRegisterBatch: (request: RegisterSourceBatchRequest_Deserialize) => typedError<RegisterSourceBatchResponse_Serialize, string>(__TAURI_INVOKE("roots.register.batch", { request })),
	/**
	 *  `roots.remap` — preview a root path remap.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	rootsRemap: (rootId: string, newPath: string) => typedError<RemapVerification, string>(__TAURI_INVOKE("roots.remap", { rootId, newPath })),
	/**
	 *  `roots.remap.apply` — apply a verified root remap.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	rootsRemapApply: (rootId: string, verified: boolean) => typedError<null, string>(__TAURI_INVOKE("roots.remap.apply", { rootId, verified })),
	/**
	 *  `scan.start` — start a filesystem scan, optionally for specific roots.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	scanStart: (rootIds: string[] | null) => typedError<IpcOperationHandle, string>(__TAURI_INVOKE("scan.start", { rootIds })),
	/**
	 *  `equipment.list` — returns all registered equipment.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	equipmentList: () => typedError<Equipment[], string>(__TAURI_INVOKE("equipment.list")),
	/**
	 *  `firstrun.state` — get the current first-run wizard state.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on database failure.
	 */
	firstrunState: () => typedError<FirstRunStateResponse_Serialize, string>(__TAURI_INVOKE("firstrun.state")),
	/**
	 *  `firstrun.complete` — mark the first-run wizard as complete.
	 * 
	 *  Requires at least one raw source and one project source to be registered.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` if preconditions are not met or on database failure.
	 */
	firstrunComplete: () => typedError<FirstRunCompleteResponse, string>(__TAURI_INVOKE("firstrun.complete")),
	/**
	 *  `firstrun.restart` — restart the first-run wizard, returning existing sources.
	 * 
	 *  Requires `confirm: true` in the request to prevent accidental restarts.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` if `confirm` is not `true` or on database failure.
	 */
	firstrunRestart: (request: FirstRunRestartRequest) => typedError<FirstRunRestartResponse, string>(__TAURI_INVOKE("firstrun.restart", { request })),
	/**
	 *  `settings.get` — returns settings for a given scope.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	settingsGet: (scope: string) => typedError<SettingsData, string>(__TAURI_INVOKE("settings.get", { scope })),
	/**
	 *  `settings.update` — update settings for a given scope.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	settingsUpdate: (scope: string, values: unknown) => typedError<null, string>(__TAURI_INVOKE("settings.update", { scope, values })),
	/**
	 *  `preferences.get` — returns current application preferences.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	preferencesGet: () => typedError<AppPreferences, string>(__TAURI_INVOKE("preferences.get")),
	/**
	 *  `preferences.set` — update a single preference key.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	preferencesSet: (key: string, value: unknown) => typedError<null, string>(__TAURI_INVOKE("preferences.set", { key, value })),
	/**
	 *  `search.global` — performs a global search across all entity types.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	searchGlobal: (query: string) => typedError<SearchResult_Serialize[], string>(__TAURI_INVOKE("search.global", { query })),
	/**
	 *  `tour.complete_step` — mark a tour step as completed.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on failure; the stub never fails.
	 */
	tourCompleteStep: (step: string) => typedError<null, string>(__TAURI_INVOKE("tour.complete_step", { step })),
	/**
	 *  `native.directory.pick` — open the OS directory picker.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on validation failure or if the dialog cannot be shown.
	 */
	nativeDirectoryPick: (request: DirectoryPickRequest_Deserialize) => typedError<DirectoryPickResponse, string>(__TAURI_INVOKE("native.directory.pick", { request })),
	/**
	 *  `native.file.pick` — open the OS file picker with type filters.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` on filter validation failure or if the dialog cannot be shown.
	 */
	nativeFilePick: (request: FilePickRequest_Deserialize) => typedError<FilePickResponse_Serialize, string>(__TAURI_INVOKE("native.file.pick", { request })),
	/**
	 *  `native.reveal` — reveal a path in the OS file browser.
	 * 
	 *  Uses `tauri_plugin_opener::reveal_item_in_dir`. On Linux, if the opener
	 *  plugin fails, falls back to `xdg-open` on the parent directory and
	 *  returns `selection: "directory_only"`.
	 * 
	 *  # Errors
	 *  Returns `Err(String)` if the path does not exist or the OS command fails.
	 */
	nativeReveal: (request: RevealRequest_Deserialize) => typedError<RevealResponse, string>(__TAURI_INVOKE("native.reveal", { request })),
};

/* Types */
/**
 *  An acquisition session as seen through the IPC boundary.
 * 
 *  This is the list-level representation returned by `sessions.list`. It
 *  matches the frontend's `AcquisitionSession` interface in `types.ts`.
 */
export type AcquisitionSession = AcquisitionSession_Serialize | AcquisitionSession_Deserialize;

/**
 *  An acquisition session as seen through the IPC boundary.
 * 
 *  This is the list-level representation returned by `sessions.list`. It
 *  matches the frontend's `AcquisitionSession` interface in `types.ts`.
 */
export type AcquisitionSession_Deserialize = {
	id: string,
	sessionKey: SessionKey,
	state: SessionState,
	confidence: ConfidenceLevel,
	opticalTrainId: string,
	frameCount: number,
	totalIntegrationSeconds: number | null,
	totalSizeBytes: number,
	metadata: { [key in string]: MetaValue_Deserialize },
	targetIds: string[],
	projectIds: string[],
	warnings: string[],
};

/**
 *  An acquisition session as seen through the IPC boundary.
 * 
 *  This is the list-level representation returned by `sessions.list`. It
 *  matches the frontend's `AcquisitionSession` interface in `types.ts`.
 */
export type AcquisitionSession_Serialize = {
	id: string,
	sessionKey: SessionKey,
	state: SessionState,
	confidence: ConfidenceLevel,
	opticalTrainId: string,
	frameCount: number,
	totalIntegrationSeconds: number | null,
	totalSizeBytes: number,
	metadata: { [key in string]: MetaValue_Serialize },
	targetIds: string[],
	projectIds: string[],
	warnings: string[],
};

/**  Application-level user preferences. */
export type AppPreferences = {
	sidebarCollapsed: boolean,
	density: Density,
	projectViewModes: { [key in string]: ViewMode },
	defaultProjectView: ViewMode,
	sessionsGroupBy: SessionsGroupBy,
	sessionsView: SessionsView,
	tourCompleted: TourCompleted,
	setupCompleted: boolean,
};

export type AssetType = "file_record" | "acquisition_session" | "calibration_session" | "project" | "prepared_source" | "processing_artifact" | "filesystem_plan" | "data_source" | 
/**  target: alias and primaryDesignation provenance tracking (R-3.2). */
"target";

/**  Actor that triggered the audited action. */
export type AuditActor = "user" | "system";

/**  A single audit log entry. */
export type AuditEntry = AuditEntry_Serialize | AuditEntry_Deserialize;

/**  A single audit log entry. */
export type AuditEntry_Deserialize = {
	id: string,
	timestamp: string,
	eventType: string,
	entityType: string,
	entityId: string,
	fromState: string | null,
	toState: string | null,
	actor: AuditActor,
	outcome: AuditOutcome,
	detail: string,
};

/**  A single audit log entry. */
export type AuditEntry_Serialize = {
	id: string,
	timestamp: string,
	eventType: string,
	entityType: string,
	entityId: string,
	fromState?: string | null,
	toState?: string | null,
	actor: AuditActor,
	outcome: AuditOutcome,
	detail: string,
};

/**  Paginated response for audit list queries. */
export type AuditListResponse = AuditListResponse_Serialize | AuditListResponse_Deserialize;

/**  Paginated response for audit list queries. */
export type AuditListResponse_Deserialize = {
	entries: AuditEntry_Deserialize[],
	total: number,
};

/**  Paginated response for audit list queries. */
export type AuditListResponse_Serialize = {
	entries: AuditEntry_Serialize[],
	total: number,
};

/**  Outcome of an audited action. */
export type AuditOutcome = "applied" | "ok" | "refused" | "failed" | "paused";

/**  Individual item result within a batch registration. */
export type BatchItem = BatchItem_Serialize | BatchItem_Deserialize;

/**  Individual item result within a batch registration. */
export type BatchItem_Deserialize = {
	index: number,
	status: ItemStatus,
	sourceId: string | null,
	error: string | null,
	errorDetail: unknown | null,
};

/**  Individual item result within a batch registration. */
export type BatchItem_Serialize = {
	index: number,
	status: ItemStatus,
	sourceId?: string | null,
	error?: string | null,
	errorDetail?: unknown | null,
};

/**  Overall batch operation status. */
export type BatchStatus = "success" | "partial" | "failure";

/**  Calendar data for the sessions calendar view. */
export type CalendarData = {
	months: CalendarMonth[],
};

/**  A single day in the session calendar. */
export type CalendarDay = {
	day: number,
	sessions: CalendarSessionStub[],
};

/**  A single month in the session calendar. */
export type CalendarMonth = {
	year: number,
	month: number,
	days: CalendarDay[],
};

/**  A session stub within a calendar day. */
export type CalendarSessionStub = {
	id: string,
	target: string,
	filter: string,
};

/**  Sensor/optical fingerprint that determines calibration compatibility. */
export type CalibrationFingerprint = CalibrationFingerprint_Serialize | CalibrationFingerprint_Deserialize;

/**  Sensor/optical fingerprint that determines calibration compatibility. */
export type CalibrationFingerprint_Deserialize = {
	camera: string,
	sensorMode: string | null,
	exposureS: number | null,
	tempC: number | null,
	gain: number | null,
	binning: string,
	filter: string | null,
};

/**  Sensor/optical fingerprint that determines calibration compatibility. */
export type CalibrationFingerprint_Serialize = {
	camera: string,
	sensorMode?: string | null,
	exposureS: number | null,
	tempC?: number | null,
	gain: number | null,
	binning: string,
	filter?: string | null,
};

/**  Kind of calibration master frame. */
export type CalibrationKind = "dark" | "flat" | "bias" | "dark_flat" | "bad_pixel_map";

/**  A calibration master as seen in list views. */
export type CalibrationMaster = CalibrationMaster_Serialize | CalibrationMaster_Deserialize;

/**  A calibration master as seen in list views. */
export type CalibrationMaster_Deserialize = {
	id: string,
	kind: CalibrationKind,
	fingerprint: CalibrationFingerprint_Deserialize,
	sourceSessionId: string,
	createdAt: string,
	ageDays: number,
	sizeBytes: number,
	usedBySessionIds: string[],
	usedByProjectIds: string[],
};

/**  A calibration master as seen in list views. */
export type CalibrationMaster_Serialize = {
	id: string,
	kind: CalibrationKind,
	fingerprint: CalibrationFingerprint_Serialize,
	sourceSessionId: string,
	createdAt: string,
	ageDays: number,
	sizeBytes: number,
	usedBySessionIds: string[],
	usedByProjectIds: string[],
};

export type CalibrationSessionTransitionRequest = CalibrationSessionTransitionRequest_Serialize | CalibrationSessionTransitionRequest_Deserialize;

export type CalibrationSessionTransitionRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: SessionState,
	nextState: SessionState,
	actionLabel: string | null,
	actor: TransitionActor,
};

export type CalibrationSessionTransitionRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: SessionState,
	nextState: SessionState,
	actionLabel?: string | null,
	actor: TransitionActor,
};

/**  Catalog identifiers for a target (NGC, IC, Messier, etc.). */
export type CatalogIds = CatalogIds_Serialize | CatalogIds_Deserialize;

/**  Catalog identifiers for a target (NGC, IC, Messier, etc.). */
export type CatalogIds_Deserialize = {
	ngc: string | null,
	ic: string | null,
	messier: string | null,
};

/**  Catalog identifiers for a target (NGC, IC, Messier, etc.). */
export type CatalogIds_Serialize = {
	ngc?: string | null,
	ic?: string | null,
	messier?: string | null,
};

/**  Cleanup eligibility for an artifact group. */
export type CleanupEligibility = "eligible" | "archive" | "keep" | "none";

/**  Cleanup state summary for a project. */
export type CleanupState = {
	reclaimableBytes: number,
};

/**  A compatible session entry within a master detail view. */
export type CompatibleSessionEntry = {
	sessionId: string,
	score: number | null,
	softMismatches: string[],
};

/**  Confidence level for inferred or reviewed metadata. */
export type ConfidenceLevel = "unknown" | "low" | "medium" | "high" | "confirmed" | "rejected";

/**  Equatorial coordinates (J2000). */
export type Coordinates = Coordinates_Serialize | Coordinates_Deserialize;

/**  Equatorial coordinates (J2000). */
export type Coordinates_Deserialize = {
	ra: number | null,
	dec: number | null,
};

/**  Equatorial coordinates (J2000). */
export type Coordinates_Serialize = {
	ra?: number | null,
	dec?: number | null,
};

export type DataSourceState = "active" | "missing" | "disabled" | "reconnect_required";

export type DataSourceTransitionRequest = DataSourceTransitionRequest_Serialize | DataSourceTransitionRequest_Deserialize;

export type DataSourceTransitionRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: DataSourceState,
	nextState: DataSourceState,
	actionLabel: string | null,
	actor: TransitionActor,
};

export type DataSourceTransitionRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: DataSourceState,
	nextState: DataSourceState,
	actionLabel?: string | null,
	actor: TransitionActor,
};

/**  UI density preference. */
export type Density = "compact" | "comfortable" | "spacious";

/**  Request payload for `native.directory.pick`. */
export type DirectoryPickRequest = DirectoryPickRequest_Serialize | DirectoryPickRequest_Deserialize;

/**  Request payload for `native.directory.pick`. */
export type DirectoryPickRequest_Deserialize = {
	requestId: string,
	defaultPath: string | null,
};

/**  Request payload for `native.directory.pick`. */
export type DirectoryPickRequest_Serialize = {
	requestId: string,
	defaultPath?: string | null,
};

/**  Response payload for `native.directory.pick`. */
export type DirectoryPickResponse = {
	/**  Absolute OS-canonical path the user selected, or `None` when cancelled. */
	path: string | null,
	/**  True when the user dismissed the dialog without selecting. */
	cancelled: boolean,
};

/**  Dry-run result summary. */
export type DryRunResult = {
	passed: number,
	warnings: number,
	failures: number,
};

/**  Entity kind for audit-log correlation on reveal operations. */
export type EntityKind = "inbox_item" | "inventory_row" | "project_manifest" | "master_calibration" | "registered_source" | "other";

/**  A piece of astrophotography equipment. */
export type Equipment = {
	id: string,
	name: string,
	kind: string,
	aliases: string[],
};

/**  A file-type filter row for the OS file picker. */
export type FileFilter = {
	/**  Display name for the filter (e.g. "FITS files"). */
	name: string,
	/**  Extensions without leading dot (e.g. `["fits", "fit"]`). */
	extensions: string[],
};

/**  Request payload for `native.file.pick`. */
export type FilePickRequest = FilePickRequest_Serialize | FilePickRequest_Deserialize;

/**  Request payload for `native.file.pick`. */
export type FilePickRequest_Deserialize = {
	requestId: string,
	/**  Ordered list of file-type filters. The first filter is the default. */
	filters: FileFilter[],
	defaultPath: string | null,
};

/**  Request payload for `native.file.pick`. */
export type FilePickRequest_Serialize = {
	requestId: string,
	/**  Ordered list of file-type filters. The first filter is the default. */
	filters: FileFilter[],
	defaultPath?: string | null,
};

/**  Response payload for `native.file.pick`. */
export type FilePickResponse = FilePickResponse_Serialize | FilePickResponse_Deserialize;

/**  Response payload for `native.file.pick`. */
export type FilePickResponse_Deserialize = {
	/**  Absolute OS-canonical path the user selected, or `None` when cancelled. */
	path: string | null,
	/**  The name of the filter active when the user clicked Open. */
	selectedFilter: string | null,
	/**  True when the user dismissed the dialog without selecting. */
	cancelled: boolean,
};

/**  Response payload for `native.file.pick`. */
export type FilePickResponse_Serialize = {
	/**  Absolute OS-canonical path the user selected, or `None` when cancelled. */
	path: string | null,
	/**  The name of the filter active when the user clicked Open. */
	selectedFilter?: string | null,
	/**  True when the user dismissed the dialog without selecting. */
	cancelled: boolean,
};

export type FileRecordState = "observed" | "missing" | "changed" | "classified" | "rejected" | "protected";

export type FileRecordTransitionRequest = FileRecordTransitionRequest_Serialize | FileRecordTransitionRequest_Deserialize;

export type FileRecordTransitionRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: FileRecordState,
	nextState: FileRecordState,
	actionLabel: string | null,
	actor: TransitionActor,
};

export type FileRecordTransitionRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: FileRecordState,
	nextState: FileRecordState,
	actionLabel?: string | null,
	actor: TransitionActor,
};

/**  A filesystem plan as seen in list/detail views. */
export type FilesystemPlan = FilesystemPlan_Serialize | FilesystemPlan_Deserialize;

/**  A filesystem plan as seen in list/detail views. */
export type FilesystemPlan_Deserialize = {
	id: string,
	kind: PlanKind,
	state: PlanState,
	items: PlanItem_Deserialize[],
	dryRunResult: DryRunResult,
	hasDestructive: boolean,
	reclaimBytes: number,
	createdAt: string,
	approvedAt: string | null,
	appliedAt: string | null,
};

/**  A filesystem plan as seen in list/detail views. */
export type FilesystemPlan_Serialize = {
	id: string,
	kind: PlanKind,
	state: PlanState,
	items: PlanItem_Serialize[],
	dryRunResult: DryRunResult,
	hasDestructive: boolean,
	reclaimBytes: number,
	createdAt: string,
	approvedAt?: string | null,
	appliedAt?: string | null,
};

/**  Response payload for `firstrun.complete`. */
export type FirstRunCompleteResponse = {
	completedAt: string,
	registeredSourceCount: number,
};

/**  Request payload for `firstrun.restart`. */
export type FirstRunRestartRequest = {
	confirm: boolean,
};

/**  Response payload for `firstrun.restart`. */
export type FirstRunRestartResponse = {
	restartedAt: string,
	prefilledSources: RegisterSourceResponse[],
};

/**  Response payload for `firstrun.state`. */
export type FirstRunStateResponse = FirstRunStateResponse_Serialize | FirstRunStateResponse_Deserialize;

/**  Response payload for `firstrun.state`. */
export type FirstRunStateResponse_Deserialize = {
	completedAt: string | null,
	lastStep: string,
};

/**  Response payload for `firstrun.state`. */
export type FirstRunStateResponse_Serialize = {
	completedAt?: string | null,
	lastStep: string,
};

/**  A group of frames within a session (per-filter breakdown). */
export type Frameset = {
	filter: string,
	count: number,
	integrationS: number | null,
};

export type InventorySessionTransitionRequest = InventorySessionTransitionRequest_Serialize | InventorySessionTransitionRequest_Deserialize;

export type InventorySessionTransitionRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: SessionState,
	nextState: SessionState,
	actionLabel: string | null,
	actor: TransitionActor,
};

export type InventorySessionTransitionRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: SessionState,
	nextState: SessionState,
	actionLabel?: string | null,
	actor: TransitionActor,
};

/**  Handle for a long-running operation (scan, plan apply, etc.). */
export type IpcOperationHandle = {
	operationId: string,
	kind: string,
};

/**  Per-item status within a batch operation. */
export type ItemStatus = "success" | "failure";

/**  JSON-friendly ledger filter mirrored to TypeScript via specta. */
export type LedgerFilterDto = {
	entityTypes?: string[],
	states?: string[],
	projectId?: string | null,
	updatedAfter?: string | null,
	updatedBefore?: string | null,
	limit?: number | null,
	offset?: number | null,
};

/**
 *  camelCase wire shape mirroring [`LedgerRow`] for the typed Tauri surface.
 * 
 *  `LedgerRow` itself doesn't derive `specta::Type` (the persistence layer
 *  stays language-internal). This DTO is the IPC projection.
 */
export type LedgerRowDto = {
	entityId: string,
	entityType: string,
	currentState: string,
	title: string | null,
	path: string | null,
	projectId: string | null,
	updatedAt: string | null,
};

/**  A registered library root directory. */
export type LibraryRoot = LibraryRoot_Serialize | LibraryRoot_Deserialize;

/**  A registered library root directory. */
export type LibraryRoot_Deserialize = {
	id: string,
	path: string,
	category: RootCategory,
	online: boolean,
	fileCount: number,
	lastScanned: string | null,
};

/**  A registered library root directory. */
export type LibraryRoot_Serialize = {
	id: string,
	path: string,
	category: RootCategory,
	online: boolean,
	fileCount: number,
	lastScanned?: string | null,
};

/**  Extended detail view of a calibration master. */
export type MasterDetail = MasterDetail_Serialize | MasterDetail_Deserialize;

/**  Extended detail view of a calibration master. */
export type MasterDetail_Deserialize = {
	id: string,
	kind: CalibrationKind,
	fingerprint: CalibrationFingerprint_Deserialize,
	sourceSessionId: string,
	createdAt: string,
	ageDays: number,
	sizeBytes: number,
	usedBySessionIds: string[],
	usedByProjectIds: string[],
	compatibleSessions: CompatibleSessionEntry[],
	usageStats: MasterUsageStats,
};

/**  Extended detail view of a calibration master. */
export type MasterDetail_Serialize = {
	id: string,
	kind: CalibrationKind,
	fingerprint: CalibrationFingerprint_Serialize,
	sourceSessionId: string,
	createdAt: string,
	ageDays: number,
	sizeBytes: number,
	usedBySessionIds: string[],
	usedByProjectIds: string[],
	compatibleSessions: CompatibleSessionEntry[],
	usageStats: MasterUsageStats,
};

/**  Usage statistics for a calibration master. */
export type MasterUsageStats = {
	sessionCount: number,
	projectCount: number,
};

/**  A candidate match between a session and a calibration master. */
export type MatchCandidate = MatchCandidate_Serialize | MatchCandidate_Deserialize;

/**  A candidate match between a session and a calibration master. */
export type MatchCandidate_Deserialize = {
	masterId: string,
	kind: CalibrationKind,
	score: number | null,
	filter: string | null,
	softMismatches: string[],
};

/**  A candidate match between a session and a calibration master. */
export type MatchCandidate_Serialize = {
	masterId: string,
	kind: CalibrationKind,
	score: number | null,
	filter?: string | null,
	softMismatches: string[],
};

/**  A single metadata value with provenance and confidence tracking. */
export type MetaValue = MetaValue_Serialize | MetaValue_Deserialize;

/**  A single metadata value with provenance and confidence tracking. */
export type MetaValue_Deserialize = {
	/**
	 *  Free-form JSON value. Uses [`crate::JsonAny`] to avoid specta's
	 *  infinite-recursion issue with raw `serde_json::Value`.
	 */
	value: unknown,
	raw: string | null,
	origin: ProvenanceOrigin,
	confidence: ConfidenceLevel,
	evidenceRef: string | null,
};

/**  A single metadata value with provenance and confidence tracking. */
export type MetaValue_Serialize = {
	/**
	 *  Free-form JSON value. Uses [`crate::JsonAny`] to avoid specta's
	 *  infinite-recursion issue with raw `serde_json::Value`.
	 */
	value: unknown,
	raw?: string | null,
	origin: ProvenanceOrigin,
	confidence: ConfidenceLevel,
	evidenceRef?: string | null,
};

/**  Verification state for a single output. */
export type OutputVerification = "accepted" | "unreviewed" | "superseded";

/**  Extended detail view of a filesystem plan. */
export type PlanDetail = PlanDetail_Serialize | PlanDetail_Deserialize;

/**  Extended detail view of a filesystem plan. */
export type PlanDetail_Deserialize = {
	id: string,
	kind: PlanKind,
	state: PlanState,
	items: PlanItem_Deserialize[],
	dryRunResult: DryRunResult,
	hasDestructive: boolean,
	reclaimBytes: number,
	createdAt: string,
	approvedAt: string | null,
	appliedAt: string | null,
	summary: PlanSafetySummary,
};

/**  Extended detail view of a filesystem plan. */
export type PlanDetail_Serialize = {
	id: string,
	kind: PlanKind,
	state: PlanState,
	items: PlanItem_Serialize[],
	dryRunResult: DryRunResult,
	hasDestructive: boolean,
	reclaimBytes: number,
	createdAt: string,
	approvedAt?: string | null,
	appliedAt?: string | null,
	summary: PlanSafetySummary,
};

/**  A single item within a filesystem plan. */
export type PlanItem = PlanItem_Serialize | PlanItem_Deserialize;

/**  Action to perform on a single filesystem item. */
export type PlanItemAction = "mkdir" | "move" | "copy" | "link" | "junction" | "write" | "archive" | "trash" | "delete";

/**  Status of a single plan item. */
export type PlanItemStatus = "pending" | "applied" | "failed" | "skipped" | "protected";

/**  A single item within a filesystem plan. */
export type PlanItem_Deserialize = {
	action: PlanItemAction,
	sourcePath: string,
	destPath: string,
	status: PlanItemStatus,
	dryRunOk: boolean,
	protectionReason: string | null,
	provenance: ProvenanceOrigin,
};

/**  A single item within a filesystem plan. */
export type PlanItem_Serialize = {
	action: PlanItemAction,
	sourcePath: string,
	destPath: string,
	status: PlanItemStatus,
	dryRunOk: boolean,
	protectionReason?: string | null,
	provenance: ProvenanceOrigin,
};

/**  Kind of filesystem plan. */
export type PlanKind = "project_structure" | "source_view" | "source_view_removal" | "archive" | "cleanup" | "root_remap" | "manifest";

/**  Safety summary for a plan detail view. */
export type PlanSafetySummary = {
	itemCount: number,
	reclaimBytes: number,
	trashCount: number,
	archiveCount: number,
	deleteCount: number,
	protectedCount: number,
};

/**  Note: `paused` is a domain-internal state (R-Pause-1); not surfaced in the transition contract. */
export type PlanState = "draft" | "ready_for_review" | "approved" | "applying" | "applied" | "partially_applied" | "failed" | "cancelled" | "discarded";

export type PlanTransitionRequest = PlanTransitionRequest_Serialize | PlanTransitionRequest_Deserialize;

export type PlanTransitionRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: PlanState,
	nextState: PlanState,
	actionLabel: string | null,
	actor: TransitionActor,
};

export type PlanTransitionRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: PlanState,
	nextState: PlanState,
	actionLabel?: string | null,
	actor: TransitionActor,
};

export type PreparedSourceState = "not_created" | "planned" | "ready" | "stale" | "retired";

export type PreparedSourceTransitionRequest = PreparedSourceTransitionRequest_Serialize | PreparedSourceTransitionRequest_Deserialize;

export type PreparedSourceTransitionRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: PreparedSourceState,
	nextState: PreparedSourceState,
	actionLabel: string | null,
	actor: TransitionActor,
};

export type PreparedSourceTransitionRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: PreparedSourceState,
	nextState: PreparedSourceState,
	actionLabel?: string | null,
	actor: TransitionActor,
};

/**  A project as seen in list views. */
export type Project = Project_Serialize | Project_Deserialize;

/**  A group of processing artifacts within a project detail view. */
export type ProjectArtifactGroup = ProjectArtifactGroup_Serialize | ProjectArtifactGroup_Deserialize;

/**  A group of processing artifacts within a project detail view. */
export type ProjectArtifactGroup_Deserialize = {
	/**  Artifact type label (e.g. "registered", "`drizzle_data`"). */
	type: string,
	count: number,
	totalSizeBytes: number,
	cleanupEligibility: CleanupEligibility,
	confidence: ConfidenceLevel,
	tool: string,
	protected: boolean,
	warning: string | null,
};

/**  A group of processing artifacts within a project detail view. */
export type ProjectArtifactGroup_Serialize = {
	/**  Artifact type label (e.g. "registered", "`drizzle_data`"). */
	type: string,
	count: number,
	totalSizeBytes: number,
	cleanupEligibility: CleanupEligibility,
	confidence: ConfidenceLevel,
	tool: string,
	protected: boolean,
	warning?: string | null,
};

/**  Extended detail view of a project. */
export type ProjectDetail = ProjectDetail_Serialize | ProjectDetail_Deserialize;

/**  Extended detail view of a project. */
export type ProjectDetail_Deserialize = {
	id: string,
	name: string,
	workflowProfileId: string,
	rootPath: string,
	state: ProjectState,
	blockedReason: string | null,
	verificationState: VerificationState,
	cleanupState: CleanupState,
	integrationHours: number | null,
	targetIds: string[],
	sourceMap: SourceMap,
	sourceViewIds: string[],
	outputIds: string[],
	processingDirectory: string,
	outputDirectory: string,
	updatedAt: string,
	targets: string[],
	sources: ProjectSource_Deserialize[],
	sourceViews: ProjectSourceView[],
	outputs: ProjectOutput[],
	artifacts: ProjectArtifactGroup_Deserialize[],
	lifecycleStageIndex: number,
	auditCount: number,
	planCount: number,
	cleanupBytes: number,
	cleanupLabel: string,
	totalIntegrationLabel: string,
	onDiskLabel: string,
	notesCount: number,
	manifestCount: number,
};

/**  Extended detail view of a project. */
export type ProjectDetail_Serialize = {
	id: string,
	name: string,
	workflowProfileId: string,
	rootPath: string,
	state: ProjectState,
	blockedReason?: string | null,
	verificationState: VerificationState,
	cleanupState: CleanupState,
	integrationHours: number | null,
	targetIds: string[],
	sourceMap: SourceMap,
	sourceViewIds: string[],
	outputIds: string[],
	processingDirectory: string,
	outputDirectory: string,
	updatedAt: string,
	targets: string[],
	sources: ProjectSource_Serialize[],
	sourceViews: ProjectSourceView[],
	outputs: ProjectOutput[],
	artifacts: ProjectArtifactGroup_Serialize[],
	lifecycleStageIndex: number,
	auditCount: number,
	planCount: number,
	cleanupBytes: number,
	cleanupLabel: string,
	totalIntegrationLabel: string,
	onDiskLabel: string,
	notesCount: number,
	manifestCount: number,
};

/**  An output artifact within a project detail view. */
export type ProjectOutput = {
	id: string,
	filename: string,
	kind: string,
	sizeBytes: number,
	date: string,
	verification: OutputVerification,
	protected: boolean,
};

/**  A source entry within a project detail view. */
export type ProjectSource = ProjectSource_Serialize | ProjectSource_Deserialize;

/**  A source view within a project detail view. */
export type ProjectSourceView = {
	name: string,
	strategy: SourceViewStrategy,
	linkCount: number,
	planRef: string,
};

/**  A source entry within a project detail view. */
export type ProjectSource_Deserialize = {
	role: SourceRole,
	name: string,
	frames: number,
	hours: string,
	selection: SourceSelection,
	warning: string | null,
};

/**  A source entry within a project detail view. */
export type ProjectSource_Serialize = {
	role: SourceRole,
	name: string,
	frames: number,
	hours: string,
	selection: SourceSelection,
	warning?: string | null,
};

export type ProjectState = "setup_incomplete" | "ready" | "prepared" | "processing" | "completed" | "archived" | "blocked";

export type ProjectTransitionRequest = ProjectTransitionRequest_Serialize | ProjectTransitionRequest_Deserialize;

export type ProjectTransitionRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: ProjectState,
	nextState: ProjectState,
	actionLabel: string | null,
	actor: TransitionActor,
};

export type ProjectTransitionRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: ProjectState,
	nextState: ProjectState,
	actionLabel?: string | null,
	actor: TransitionActor,
};

/**  A project as seen in list views. */
export type Project_Deserialize = {
	id: string,
	name: string,
	workflowProfileId: string,
	rootPath: string,
	state: ProjectState,
	blockedReason: string | null,
	verificationState: VerificationState,
	cleanupState: CleanupState,
	integrationHours: number | null,
	targetIds: string[],
	sourceMap: SourceMap,
	sourceViewIds: string[],
	outputIds: string[],
	processingDirectory: string,
	outputDirectory: string,
	updatedAt: string,
};

/**  A project as seen in list views. */
export type Project_Serialize = {
	id: string,
	name: string,
	workflowProfileId: string,
	rootPath: string,
	state: ProjectState,
	blockedReason?: string | null,
	verificationState: VerificationState,
	cleanupState: CleanupState,
	integrationHours: number | null,
	targetIds: string[],
	sourceMap: SourceMap,
	sourceViewIds: string[],
	outputIds: string[],
	processingDirectory: string,
	outputDirectory: string,
	updatedAt: string,
};

export type ProjectionState = "current" | "stale" | "regenerating";

export type ProjectionTransitionRequest = ProjectionTransitionRequest_Serialize | ProjectionTransitionRequest_Deserialize;

export type ProjectionTransitionRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: ProjectionState,
	nextState: ProjectionState,
	actionLabel: string | null,
	actor: TransitionActor,
};

export type ProjectionTransitionRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: ProjectionState,
	nextState: ProjectionState,
	actionLabel?: string | null,
	actor: TransitionActor,
};

export type ProvenanceError = ProvenanceError_Serialize | ProvenanceError_Deserialize;

export type ProvenanceErrorCode = "asset_not_found" | "actor_not_authorised";

export type ProvenanceError_Deserialize = {
	code: ProvenanceErrorCode,
	message: string,
	details: unknown | null,
};

export type ProvenanceError_Serialize = {
	code: ProvenanceErrorCode,
	message: string,
	details?: unknown | null,
};

export type ProvenanceField = ProvenanceField_Serialize | ProvenanceField_Deserialize;

export type ProvenanceField_Deserialize = {
	fieldPath: string,
	current: unknown,
	origin: ProvenanceOrigin,
	capturedAt: string,
	sourceId: string | null,
	history: ProvenanceHistoryEntry_Deserialize[],
	historyTruncated?: boolean,
};

export type ProvenanceField_Serialize = {
	fieldPath: string,
	current: unknown,
	origin: ProvenanceOrigin,
	capturedAt: string,
	sourceId?: string | null,
	history: ProvenanceHistoryEntry_Serialize[],
	historyTruncated: boolean,
};

export type ProvenanceHistoryEntry = ProvenanceHistoryEntry_Serialize | ProvenanceHistoryEntry_Deserialize;

export type ProvenanceHistoryEntry_Deserialize = {
	origin: ProvenanceOrigin,
	value: unknown,
	capturedAt: string,
	sourceId: string | null,
	replacedBy: string | null,
};

export type ProvenanceHistoryEntry_Serialize = {
	origin: ProvenanceOrigin,
	value: unknown,
	capturedAt: string,
	sourceId?: string | null,
	replacedBy?: string | null,
};

export type ProvenanceOrigin = "observed" | "inferred" | "reviewed" | "generated" | "planned" | "applied";

export type ProvenanceReadRequest = ProvenanceReadRequest_Serialize | ProvenanceReadRequest_Deserialize;

export type ProvenanceReadRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	assetId: string,
	assetType: AssetType,
	fieldPaths?: string[],
};

export type ProvenanceReadRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	assetId: string,
	assetType: AssetType,
	fieldPaths?: string[],
};

export type ProvenanceReadResponse = ProvenanceReadResponse_Serialize | ProvenanceReadResponse_Deserialize;

export type ProvenanceReadResponse_Deserialize = {
	status: ProvenanceResponseStatus,
	contractVersion: string,
	requestId: string,
	assetId: string | null,
	assetType: AssetType | null,
	provenance: ProvenanceField_Deserialize[] | null,
	error: ProvenanceError_Deserialize | null,
};

export type ProvenanceReadResponse_Serialize = {
	status: ProvenanceResponseStatus,
	contractVersion: string,
	requestId: string,
	assetId?: string | null,
	assetType?: AssetType | null,
	provenance?: ProvenanceField_Serialize[] | null,
	error?: ProvenanceError_Serialize | null,
};

export type ProvenanceResponseStatus = "success" | "error";

/**  Request payload for `roots.register.batch`. */
export type RegisterSourceBatchRequest = RegisterSourceBatchRequest_Serialize | RegisterSourceBatchRequest_Deserialize;

/**  Request payload for `roots.register.batch`. */
export type RegisterSourceBatchRequest_Deserialize = {
	sources: RegisterSourceRequest_Deserialize[],
};

/**  Request payload for `roots.register.batch`. */
export type RegisterSourceBatchRequest_Serialize = {
	sources: RegisterSourceRequest_Serialize[],
};

/**  Response payload for `roots.register.batch`. */
export type RegisterSourceBatchResponse = RegisterSourceBatchResponse_Serialize | RegisterSourceBatchResponse_Deserialize;

/**  Response payload for `roots.register.batch`. */
export type RegisterSourceBatchResponse_Deserialize = {
	status: BatchStatus,
	items: BatchItem_Deserialize[],
};

/**  Response payload for `roots.register.batch`. */
export type RegisterSourceBatchResponse_Serialize = {
	status: BatchStatus,
	items: BatchItem_Serialize[],
};

/**  Request payload for `roots.register`. */
export type RegisterSourceRequest = RegisterSourceRequest_Serialize | RegisterSourceRequest_Deserialize;

/**  Request payload for `roots.register`. */
export type RegisterSourceRequest_Deserialize = {
	kind: SourceKind,
	path: string,
	kindSubtype: string | null,
	scanDepth: ScanDepth,
};

/**  Request payload for `roots.register`. */
export type RegisterSourceRequest_Serialize = {
	kind: SourceKind,
	path: string,
	kindSubtype?: string | null,
	scanDepth: ScanDepth,
};

/**  Response payload for `roots.register`. */
export type RegisterSourceResponse = {
	sourceId: string,
	kind: SourceKind,
	path: string,
	createdAt: string,
};

/**  A sample path match result within a remap verification. */
export type RemapSample = {
	relativePath: string,
	found: boolean,
};

/**  Verification result for a root path remap operation. */
export type RemapVerification = {
	rootId: string,
	originalPath: string,
	newPath: string,
	samples: RemapSample[],
	allVerified: boolean,
};

/**  Request payload for `native.reveal`. */
export type RevealRequest = RevealRequest_Serialize | RevealRequest_Deserialize;

/**  Request payload for `native.reveal`. */
export type RevealRequest_Deserialize = {
	requestId: string,
	/**  Absolute path to reveal. May point to a file or directory. */
	path: string,
	/**  Optional context tag for audit-log correlation. */
	entityKind: EntityKind | null,
	/**  Optional entity identifier for audit-log correlation. */
	entityId: string | null,
};

/**  Request payload for `native.reveal`. */
export type RevealRequest_Serialize = {
	requestId: string,
	/**  Absolute path to reveal. May point to a file or directory. */
	path: string,
	/**  Optional context tag for audit-log correlation. */
	entityKind?: EntityKind | null,
	/**  Optional entity identifier for audit-log correlation. */
	entityId?: string | null,
};

/**  Response payload for `native.reveal`. */
export type RevealResponse = {
	/**  True when the OS file browser launched successfully. */
	revealed: boolean,
	/**  How the target was highlighted. */
	selection: RevealSelection,
};

/**  How the target was highlighted in the OS file browser after a reveal. */
export type RevealSelection = 
/**  The item was selected in the file browser (macOS, Windows, Linux freedesktop). */
"target" | 
/**  Only the parent directory opened (Linux xdg-open fallback). */
"directory_only" | 
/**  No UI hint was applied. */
"none";

/**  An item in the review queue awaiting user decision. */
export type ReviewItem = ReviewItem_Serialize | ReviewItem_Deserialize;

/**  Kind of item in the review queue. */
export type ReviewItemKind = "session" | "unclassified_file";

/**  An item in the review queue awaiting user decision. */
export type ReviewItem_Deserialize = {
	id: string,
	kind: ReviewItemKind,
	sessionId: string | null,
	filePath: string | null,
	confidence: ConfidenceLevel,
	blockingReasons: string[],
	evidence: { [key in string]: MetaValue_Deserialize },
	suggestedTarget: string | null,
	suggestedFilter: string | null,
};

/**  An item in the review queue awaiting user decision. */
export type ReviewItem_Serialize = {
	id: string,
	kind: ReviewItemKind,
	sessionId?: string | null,
	filePath?: string | null,
	confidence: ConfidenceLevel,
	blockingReasons: string[],
	evidence: { [key in string]: MetaValue_Serialize },
	suggestedTarget?: string | null,
	suggestedFilter?: string | null,
};

/**  Category of a library root directory. */
export type RootCategory = "raw" | "calibration" | "project" | "inbox";

/**  Scan depth strategy for a registered source. */
export type ScanDepth = "recursive" | "single";

/**  A single search result from global search. */
export type SearchResult = SearchResult_Serialize | SearchResult_Deserialize;

/**  Kind of entity returned by a global search. */
export type SearchResultKind = "session" | "target" | "project" | "page" | "action";

/**  A single search result from global search. */
export type SearchResult_Deserialize = {
	id: string,
	kind: SearchResultKind,
	label: string,
	sublabel: string | null,
	route: string,
	score: number | null,
};

/**  A single search result from global search. */
export type SearchResult_Serialize = {
	id: string,
	kind: SearchResultKind,
	label: string,
	sublabel?: string | null,
	route: string,
	score: number | null,
};

/**  A calibration match entry for a session detail view. */
export type SessionCalibrationMatch = {
	masterId: string,
	kind: CalibrationKind,
	score: number | null,
	softMismatches: string[],
};

/**  Extended detail view of an acquisition session. */
export type SessionDetail = SessionDetail_Serialize | SessionDetail_Deserialize;

/**  Extended detail view of an acquisition session. */
export type SessionDetail_Deserialize = {
	id: string,
	sessionKey: SessionKey,
	state: SessionState,
	confidence: ConfidenceLevel,
	opticalTrainId: string,
	frameCount: number,
	totalIntegrationSeconds: number | null,
	totalSizeBytes: number,
	metadata: { [key in string]: MetaValue_Deserialize },
	targetIds: string[],
	projectIds: string[],
	warnings: string[],
	framesets: Frameset[],
	calibrationMatches: SessionCalibrationMatch[],
	history: SessionHistoryEntry[],
};

/**  Extended detail view of an acquisition session. */
export type SessionDetail_Serialize = {
	id: string,
	sessionKey: SessionKey,
	state: SessionState,
	confidence: ConfidenceLevel,
	opticalTrainId: string,
	frameCount: number,
	totalIntegrationSeconds: number | null,
	totalSizeBytes: number,
	metadata: { [key in string]: MetaValue_Serialize },
	targetIds: string[],
	projectIds: string[],
	warnings: string[],
	framesets: Frameset[],
	calibrationMatches: SessionCalibrationMatch[],
	history: SessionHistoryEntry[],
};

/**  A history entry for a session detail view. */
export type SessionHistoryEntry = {
	timestamp: string,
	event: string,
	actor: string,
};

/**
 *  Composite key that uniquely identifies an acquisition session by its
 *  observing parameters.
 */
export type SessionKey = {
	target: string,
	filter: string,
	binning: string,
	gain: string,
	/**  ISO date of the observing night (local sunset date). */
	night: string,
};

/**  Wrapper for `sessions.split` return value. */
export type SessionSplitResult = SessionSplitResult_Serialize | SessionSplitResult_Deserialize;

/**  Wrapper for `sessions.split` return value. */
export type SessionSplitResult_Deserialize = {
	original: AcquisitionSession_Deserialize,
	new: AcquisitionSession_Deserialize,
};

/**  Wrapper for `sessions.split` return value. */
export type SessionSplitResult_Serialize = {
	original: AcquisitionSession_Serialize,
	new: AcquisitionSession_Serialize,
};

export type SessionState = "discovered" | "candidate" | "needs_review" | "confirmed" | "rejected" | "ignored";

/**  Sessions grouping mode. */
export type SessionsGroupBy = "none" | "target" | "month" | "filter" | "train";

/**  Sessions view mode. */
export type SessionsView = "list" | "calendar";

/**
 *  Scoped settings data (general, naming, calibration, etc.).
 * 
 *  `values` is a free-form JSON object keyed by setting name.
 */
export type SettingsData = {
	scope: string,
	values: unknown,
};

/**  Kind of a registered source directory. */
export type SourceKind = "raw" | "calibration" | "project" | "inbox";

/**  Map of calibration frame roles to file paths within a project. */
export type SourceMap = {
	lights: string[],
	darks: string[],
	flats: string[],
	bias: string[],
	darkFlats: string[],
};

/**  Role of a source within a project. */
export type SourceRole = "light" | "dark" | "flat" | "bias";

/**  Selection state for a source within a project. */
export type SourceSelection = "selected" | "candidate";

/**  Link strategy for a source view. */
export type SourceViewStrategy = "junction" | "symlink" | "hardlink" | "copy";

/**  An astronomical target as seen in list views. */
export type Target = Target_Serialize | Target_Deserialize;

/**  Extended detail view of a target. */
export type TargetDetail = TargetDetail_Serialize | TargetDetail_Deserialize;

/**  Extended detail view of a target. */
export type TargetDetail_Deserialize = {
	id: string,
	name: string,
	aliases: string[],
	catalogIds: CatalogIds_Deserialize,
	kind: TargetKind,
	coordinates: Coordinates_Deserialize | null,
	sessionCount: number,
	projectCount: number,
	totalIntegrationHours: number | null,
	coverage: { [key in string]: number | null },
	recommendedHours: { [key in string]: number | null },
	sessions: AcquisitionSession_Deserialize[],
	projects: TargetProjectStub[],
};

/**  Extended detail view of a target. */
export type TargetDetail_Serialize = {
	id: string,
	name: string,
	aliases: string[],
	catalogIds: CatalogIds_Serialize,
	kind: TargetKind,
	coordinates?: Coordinates_Serialize | null,
	sessionCount: number,
	projectCount: number,
	totalIntegrationHours: number | null,
	coverage: { [key in string]: number | null },
	recommendedHours: { [key in string]: number | null },
	sessions: AcquisitionSession_Serialize[],
	projects: TargetProjectStub[],
};

/**  Classification of an astronomical target. */
export type TargetKind = "deep_sky" | "planetary" | "lunar" | "solar" | "landscape";

/**  A project stub within the target detail view. */
export type TargetProjectStub = {
	id: string,
	name: string,
	state: ProjectState,
};

/**  An astronomical target as seen in list views. */
export type Target_Deserialize = {
	id: string,
	name: string,
	aliases: string[],
	catalogIds: CatalogIds_Deserialize,
	kind: TargetKind,
	coordinates: Coordinates_Deserialize | null,
	sessionCount: number,
	projectCount: number,
	totalIntegrationHours: number | null,
	/**  Filter name -> acquired hours. */
	coverage: { [key in string]: number | null },
	/**  Filter name -> recommended hours. */
	recommendedHours: { [key in string]: number | null },
};

/**  An astronomical target as seen in list views. */
export type Target_Serialize = {
	id: string,
	name: string,
	aliases: string[],
	catalogIds: CatalogIds_Serialize,
	kind: TargetKind,
	coordinates?: Coordinates_Serialize | null,
	sessionCount: number,
	projectCount: number,
	totalIntegrationHours: number | null,
	/**  Filter name -> acquired hours. */
	coverage: { [key in string]: number | null },
	/**  Filter name -> recommended hours. */
	recommendedHours: { [key in string]: number | null },
};

/**  Tour completion state tracking. */
export type TourCompleted = {
	step1: boolean,
	step2: boolean,
	step3: boolean,
};

export type TransitionActor = "user" | "system";

export type TransitionError = TransitionError_Serialize | TransitionError_Deserialize;

export type TransitionErrorCode = "transition.refused" | "entity.not_found" | "actor.not_authorised" | "plan.required" | "plan.not_approved" | "provenance.unreviewed";

export type TransitionError_Deserialize = {
	code: TransitionErrorCode,
	message: string,
	details: unknown | null,
};

export type TransitionError_Serialize = {
	code: TransitionErrorCode,
	message: string,
	details?: unknown | null,
};

/**  Discriminated request — one variant per entity family. */
export type TransitionRequest = TransitionRequest_Serialize | TransitionRequest_Deserialize;

/**  Discriminated request — one variant per entity family. */
export type TransitionRequest_Deserialize = ({ project: {
	entityType: "project",
} & ProjectTransitionRequest_Deserialize }) & { calibration_session?: never; data_source?: never; file_record?: never; inventory_session?: never; plan?: never; prepared_source?: never; projection?: never } | ({ plan: {
	entityType: "plan",
} & PlanTransitionRequest_Deserialize }) & { calibration_session?: never; data_source?: never; file_record?: never; inventory_session?: never; prepared_source?: never; project?: never; projection?: never } | ({ inventory_session: {
	entityType: "inventory_session",
} & InventorySessionTransitionRequest_Deserialize }) & { calibration_session?: never; data_source?: never; file_record?: never; plan?: never; prepared_source?: never; project?: never; projection?: never } | ({ calibration_session: {
	entityType: "calibration_session",
} & CalibrationSessionTransitionRequest_Deserialize }) & { data_source?: never; file_record?: never; inventory_session?: never; plan?: never; prepared_source?: never; project?: never; projection?: never } | ({ data_source: {
	entityType: "data_source",
} & DataSourceTransitionRequest_Deserialize }) & { calibration_session?: never; file_record?: never; inventory_session?: never; plan?: never; prepared_source?: never; project?: never; projection?: never } | ({ prepared_source: {
	entityType: "prepared_source",
} & PreparedSourceTransitionRequest_Deserialize }) & { calibration_session?: never; data_source?: never; file_record?: never; inventory_session?: never; plan?: never; project?: never; projection?: never } | ({ projection: {
	entityType: "projection",
} & ProjectionTransitionRequest_Deserialize }) & { calibration_session?: never; data_source?: never; file_record?: never; inventory_session?: never; plan?: never; prepared_source?: never; project?: never } | ({ file_record: {
	entityType: "file_record",
} & FileRecordTransitionRequest_Deserialize }) & { calibration_session?: never; data_source?: never; inventory_session?: never; plan?: never; prepared_source?: never; project?: never; projection?: never };

/**  Discriminated request — one variant per entity family. */
export type TransitionRequest_Serialize = ({ project: {
	entityType: "project",
} & ProjectTransitionRequest_Serialize }) & { calibration_session?: never; data_source?: never; file_record?: never; inventory_session?: never; plan?: never; prepared_source?: never; projection?: never } | ({ plan: {
	entityType: "plan",
} & PlanTransitionRequest_Serialize }) & { calibration_session?: never; data_source?: never; file_record?: never; inventory_session?: never; prepared_source?: never; project?: never; projection?: never } | ({ inventory_session: {
	entityType: "inventory_session",
} & InventorySessionTransitionRequest_Serialize }) & { calibration_session?: never; data_source?: never; file_record?: never; plan?: never; prepared_source?: never; project?: never; projection?: never } | ({ calibration_session: {
	entityType: "calibration_session",
} & CalibrationSessionTransitionRequest_Serialize }) & { data_source?: never; file_record?: never; inventory_session?: never; plan?: never; prepared_source?: never; project?: never; projection?: never } | ({ data_source: {
	entityType: "data_source",
} & DataSourceTransitionRequest_Serialize }) & { calibration_session?: never; file_record?: never; inventory_session?: never; plan?: never; prepared_source?: never; project?: never; projection?: never } | ({ prepared_source: {
	entityType: "prepared_source",
} & PreparedSourceTransitionRequest_Serialize }) & { calibration_session?: never; data_source?: never; file_record?: never; inventory_session?: never; plan?: never; project?: never; projection?: never } | ({ projection: {
	entityType: "projection",
} & ProjectionTransitionRequest_Serialize }) & { calibration_session?: never; data_source?: never; file_record?: never; inventory_session?: never; plan?: never; prepared_source?: never; project?: never } | ({ file_record: {
	entityType: "file_record",
} & FileRecordTransitionRequest_Serialize }) & { calibration_session?: never; data_source?: never; inventory_session?: never; plan?: never; prepared_source?: never; project?: never; projection?: never };

export type TransitionResponse = TransitionResponse_Serialize | TransitionResponse_Deserialize;

export type TransitionResponse_Deserialize = {
	status: TransitionStatus,
	contractVersion: string,
	requestId: string,
	appliedAt: string | null,
	priorState: string | null,
	newState: string | null,
	auditId: string | null,
	planId: string | null,
	error: TransitionError_Deserialize | null,
};

export type TransitionResponse_Serialize = {
	status: TransitionStatus,
	contractVersion: string,
	requestId: string,
	appliedAt?: string | null,
	priorState?: string | null,
	newState?: string | null,
	auditId?: string | null,
	planId?: string | null,
	error?: TransitionError_Serialize | null,
};

export type TransitionStatus = "success" | "noop" | "error";

/**  Verification state for a project's outputs. */
export type VerificationState = "unreviewed" | "has_accepted" | "all_rejected";

/**  Project detail view mode. */
export type ViewMode = "center" | "pipeline" | "combined";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

