// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  `provenance.read` Tauri command — returns the contract response shape.
	 * 
	 *  # Errors
	 *  Never returns `Err`; persistence failures are folded into
	 *  `ProvenanceReadResponse::error(...)`. The `Result` shape exists so the
	 *  frontend's invoke wrapper still gets a typed envelope.
	 */
	provenanceRead: (request: ProvenanceReadRequest_Deserialize) => typedError<ProvenanceReadResponse_Serialize, string>(__TAURI_INVOKE("provenance_read", { request })),
	/**
	 *  `lifecycle.transition.apply` Tauri command.
	 * 
	 *  # Errors
	 *  Never returns `Err`; refusal / persistence errors fold into
	 *  `TransitionResponse::error(...)` per the contract.
	 */
	lifecycleTransitionApply: (request: TransitionRequest_Deserialize) => typedError<TransitionResponse_Serialize, string>(__TAURI_INVOKE("lifecycle_transition_apply", { request })),
	/**
	 *  `lifecycle.transition.preview` — read-only dry-run for UI button enabling.
	 * 
	 *  # Errors
	 *  Never returns `Err`; refusal codes fold into `TransitionResponse::error(...)`.
	 */
	lifecycleTransitionPreview: (request: TransitionRequest_Deserialize) => typedError<TransitionResponse_Serialize, string>(__TAURI_INVOKE("lifecycle_transition_preview", { request })),
	/**
	 *  `lifecycle.ledger.list` Tauri command.
	 * 
	 *  # Errors
	 *  Returns a stringified persistence error when the repository query fails
	 *  (e.g. transient DB unavailability). Successful empty results are `Ok(vec![])`.
	 */
	lifecycleLedgerList: (filter: LedgerFilterDto) => typedError<LedgerRowDto[], string>(__TAURI_INVOKE("lifecycle_ledger_list", { filter })),
};

/* Types */
export type AssetType = "file_record" | "acquisition_session" | "calibration_session" | "project" | "prepared_source" | "processing_artifact" | "filesystem_plan" | "data_source" | 
/**  target: alias and primaryDesignation provenance tracking (R-3.2). */
"target";

export type CalibrationSessionTransitionRequest = CalibrationSessionTransitionRequest_Serialize | CalibrationSessionTransitionRequest_Deserialize;

export type CalibrationSessionTransitionRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: SessionState,
	nextState: SessionState,
	actionLabel: string | null,
	actor: TransitionActor,
};

export type CalibrationSessionTransitionRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: SessionState,
	nextState: SessionState,
	actionLabel?: string | null,
	actor: TransitionActor,
};

export type DataSourceState = "active" | "missing" | "disabled" | "reconnect_required";

export type DataSourceTransitionRequest = DataSourceTransitionRequest_Serialize | DataSourceTransitionRequest_Deserialize;

export type DataSourceTransitionRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: DataSourceState,
	nextState: DataSourceState,
	actionLabel: string | null,
	actor: TransitionActor,
};

export type DataSourceTransitionRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: DataSourceState,
	nextState: DataSourceState,
	actionLabel?: string | null,
	actor: TransitionActor,
};

export type FileRecordState = "observed" | "missing" | "changed" | "classified" | "rejected" | "protected";

export type FileRecordTransitionRequest = FileRecordTransitionRequest_Serialize | FileRecordTransitionRequest_Deserialize;

export type FileRecordTransitionRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: FileRecordState,
	nextState: FileRecordState,
	actionLabel: string | null,
	actor: TransitionActor,
};

export type FileRecordTransitionRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: FileRecordState,
	nextState: FileRecordState,
	actionLabel?: string | null,
	actor: TransitionActor,
};

export type InventorySessionTransitionRequest = InventorySessionTransitionRequest_Serialize | InventorySessionTransitionRequest_Deserialize;

export type InventorySessionTransitionRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: SessionState,
	nextState: SessionState,
	actionLabel: string | null,
	actor: TransitionActor,
};

export type InventorySessionTransitionRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: SessionState,
	nextState: SessionState,
	actionLabel?: string | null,
	actor: TransitionActor,
};

/**  JSON-friendly ledger filter mirrored to TypeScript via specta. */
export type LedgerFilterDto = {
	entityTypes?: string[],
	states?: string[],
	projectId?: string | null,
	updatedAfter?: string | null,
	updatedBefore?: string | null,
	limit?: number | null,
	offset?: number | null,
};

/**
 *  camelCase wire shape mirroring [`LedgerRow`] for the typed Tauri surface.
 * 
 *  `LedgerRow` itself doesn't derive `specta::Type` (the persistence layer
 *  stays language-internal). This DTO is the IPC projection.
 */
export type LedgerRowDto = {
	entityId: string,
	entityType: string,
	currentState: string,
	title: string | null,
	path: string | null,
	projectId: string | null,
	updatedAt: string | null,
};

/**  Note: `paused` is a domain-internal state (R-Pause-1); not surfaced in the transition contract. */
export type PlanState = "draft" | "ready_for_review" | "approved" | "applying" | "applied" | "partially_applied" | "failed" | "cancelled" | "discarded";

export type PlanTransitionRequest = PlanTransitionRequest_Serialize | PlanTransitionRequest_Deserialize;

export type PlanTransitionRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: PlanState,
	nextState: PlanState,
	actionLabel: string | null,
	actor: TransitionActor,
};

export type PlanTransitionRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: PlanState,
	nextState: PlanState,
	actionLabel?: string | null,
	actor: TransitionActor,
};

export type PreparedSourceState = "not_created" | "planned" | "ready" | "stale" | "retired";

export type PreparedSourceTransitionRequest = PreparedSourceTransitionRequest_Serialize | PreparedSourceTransitionRequest_Deserialize;

export type PreparedSourceTransitionRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: PreparedSourceState,
	nextState: PreparedSourceState,
	actionLabel: string | null,
	actor: TransitionActor,
};

export type PreparedSourceTransitionRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: PreparedSourceState,
	nextState: PreparedSourceState,
	actionLabel?: string | null,
	actor: TransitionActor,
};

export type ProjectState = "setup_incomplete" | "ready" | "prepared" | "processing" | "completed" | "archived" | "blocked";

export type ProjectTransitionRequest = ProjectTransitionRequest_Serialize | ProjectTransitionRequest_Deserialize;

export type ProjectTransitionRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: ProjectState,
	nextState: ProjectState,
	actionLabel: string | null,
	actor: TransitionActor,
};

export type ProjectTransitionRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: ProjectState,
	nextState: ProjectState,
	actionLabel?: string | null,
	actor: TransitionActor,
};

export type ProjectionState = "current" | "stale" | "regenerating";

export type ProjectionTransitionRequest = ProjectionTransitionRequest_Serialize | ProjectionTransitionRequest_Deserialize;

export type ProjectionTransitionRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: ProjectionState,
	nextState: ProjectionState,
	actionLabel: string | null,
	actor: TransitionActor,
};

export type ProjectionTransitionRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	entityType: string,
	entityId: string,
	currentState: ProjectionState,
	nextState: ProjectionState,
	actionLabel?: string | null,
	actor: TransitionActor,
};

export type ProvenanceError = ProvenanceError_Serialize | ProvenanceError_Deserialize;

export type ProvenanceErrorCode = "asset_not_found" | "actor_not_authorised";

export type ProvenanceError_Deserialize = {
	code: ProvenanceErrorCode,
	message: string,
	details: unknown | null,
};

export type ProvenanceError_Serialize = {
	code: ProvenanceErrorCode,
	message: string,
	details?: unknown | null,
};

export type ProvenanceField = ProvenanceField_Serialize | ProvenanceField_Deserialize;

export type ProvenanceField_Deserialize = {
	fieldPath: string,
	current: unknown,
	origin: ProvenanceOrigin,
	capturedAt: string,
	sourceId: string | null,
	history: ProvenanceHistoryEntry_Deserialize[],
	historyTruncated?: boolean,
};

export type ProvenanceField_Serialize = {
	fieldPath: string,
	current: unknown,
	origin: ProvenanceOrigin,
	capturedAt: string,
	sourceId?: string | null,
	history: ProvenanceHistoryEntry_Serialize[],
	historyTruncated: boolean,
};

export type ProvenanceHistoryEntry = ProvenanceHistoryEntry_Serialize | ProvenanceHistoryEntry_Deserialize;

export type ProvenanceHistoryEntry_Deserialize = {
	origin: ProvenanceOrigin,
	value: unknown,
	capturedAt: string,
	sourceId: string | null,
	replacedBy: string | null,
};

export type ProvenanceHistoryEntry_Serialize = {
	origin: ProvenanceOrigin,
	value: unknown,
	capturedAt: string,
	sourceId?: string | null,
	replacedBy?: string | null,
};

export type ProvenanceOrigin = "observed" | "inferred" | "reviewed" | "generated" | "planned" | "applied";

export type ProvenanceReadRequest = ProvenanceReadRequest_Serialize | ProvenanceReadRequest_Deserialize;

export type ProvenanceReadRequest_Deserialize = {
	contractVersion: string,
	requestId: string,
	assetId: string,
	assetType: AssetType,
	fieldPaths?: string[],
};

export type ProvenanceReadRequest_Serialize = {
	contractVersion: string,
	requestId: string,
	assetId: string,
	assetType: AssetType,
	fieldPaths?: string[],
};

export type ProvenanceReadResponse = ProvenanceReadResponse_Serialize | ProvenanceReadResponse_Deserialize;

export type ProvenanceReadResponse_Deserialize = {
	status: ProvenanceResponseStatus,
	contractVersion: string,
	requestId: string,
	assetId: string | null,
	assetType: AssetType | null,
	provenance: ProvenanceField_Deserialize[] | null,
	error: ProvenanceError_Deserialize | null,
};

export type ProvenanceReadResponse_Serialize = {
	status: ProvenanceResponseStatus,
	contractVersion: string,
	requestId: string,
	assetId?: string | null,
	assetType?: AssetType | null,
	provenance?: ProvenanceField_Serialize[] | null,
	error?: ProvenanceError_Serialize | null,
};

export type ProvenanceResponseStatus = "success" | "error";

export type SessionState = "discovered" | "candidate" | "needs_review" | "confirmed" | "rejected" | "ignored";

export type TransitionActor = "user" | "system";

export type TransitionError = TransitionError_Serialize | TransitionError_Deserialize;

export type TransitionErrorCode = "transition.refused" | "entity.not_found" | "actor.not_authorised" | "plan.required" | "plan.not_approved" | "provenance.unreviewed";

export type TransitionError_Deserialize = {
	code: TransitionErrorCode,
	message: string,
	details: unknown | null,
};

export type TransitionError_Serialize = {
	code: TransitionErrorCode,
	message: string,
	details?: unknown | null,
};

/**  Discriminated request — one variant per entity family. */
export type TransitionRequest = TransitionRequest_Serialize | TransitionRequest_Deserialize;

/**  Discriminated request — one variant per entity family. */
export type TransitionRequest_Deserialize = ({ project: {
	entityType: "project",
} & ProjectTransitionRequest_Deserialize }) & { calibration_session?: never; data_source?: never; file_record?: never; inventory_session?: never; plan?: never; prepared_source?: never; projection?: never } | ({ plan: {
	entityType: "plan",
} & PlanTransitionRequest_Deserialize }) & { calibration_session?: never; data_source?: never; file_record?: never; inventory_session?: never; prepared_source?: never; project?: never; projection?: never } | ({ inventory_session: {
	entityType: "inventory_session",
} & InventorySessionTransitionRequest_Deserialize }) & { calibration_session?: never; data_source?: never; file_record?: never; plan?: never; prepared_source?: never; project?: never; projection?: never } | ({ calibration_session: {
	entityType: "calibration_session",
} & CalibrationSessionTransitionRequest_Deserialize }) & { data_source?: never; file_record?: never; inventory_session?: never; plan?: never; prepared_source?: never; project?: never; projection?: never } | ({ data_source: {
	entityType: "data_source",
} & DataSourceTransitionRequest_Deserialize }) & { calibration_session?: never; file_record?: never; inventory_session?: never; plan?: never; prepared_source?: never; project?: never; projection?: never } | ({ prepared_source: {
	entityType: "prepared_source",
} & PreparedSourceTransitionRequest_Deserialize }) & { calibration_session?: never; data_source?: never; file_record?: never; inventory_session?: never; plan?: never; project?: never; projection?: never } | ({ projection: {
	entityType: "projection",
} & ProjectionTransitionRequest_Deserialize }) & { calibration_session?: never; data_source?: never; file_record?: never; inventory_session?: never; plan?: never; prepared_source?: never; project?: never } | ({ file_record: {
	entityType: "file_record",
} & FileRecordTransitionRequest_Deserialize }) & { calibration_session?: never; data_source?: never; inventory_session?: never; plan?: never; prepared_source?: never; project?: never; projection?: never };

/**  Discriminated request — one variant per entity family. */
export type TransitionRequest_Serialize = ({ project: {
	entityType: "project",
} & ProjectTransitionRequest_Serialize }) & { calibration_session?: never; data_source?: never; file_record?: never; inventory_session?: never; plan?: never; prepared_source?: never; projection?: never } | ({ plan: {
	entityType: "plan",
} & PlanTransitionRequest_Serialize }) & { calibration_session?: never; data_source?: never; file_record?: never; inventory_session?: never; prepared_source?: never; project?: never; projection?: never } | ({ inventory_session: {
	entityType: "inventory_session",
} & InventorySessionTransitionRequest_Serialize }) & { calibration_session?: never; data_source?: never; file_record?: never; plan?: never; prepared_source?: never; project?: never; projection?: never } | ({ calibration_session: {
	entityType: "calibration_session",
} & CalibrationSessionTransitionRequest_Serialize }) & { data_source?: never; file_record?: never; inventory_session?: never; plan?: never; prepared_source?: never; project?: never; projection?: never } | ({ data_source: {
	entityType: "data_source",
} & DataSourceTransitionRequest_Serialize }) & { calibration_session?: never; file_record?: never; inventory_session?: never; plan?: never; prepared_source?: never; project?: never; projection?: never } | ({ prepared_source: {
	entityType: "prepared_source",
} & PreparedSourceTransitionRequest_Serialize }) & { calibration_session?: never; data_source?: never; file_record?: never; inventory_session?: never; plan?: never; project?: never; projection?: never } | ({ projection: {
	entityType: "projection",
} & ProjectionTransitionRequest_Serialize }) & { calibration_session?: never; data_source?: never; file_record?: never; inventory_session?: never; plan?: never; prepared_source?: never; project?: never } | ({ file_record: {
	entityType: "file_record",
} & FileRecordTransitionRequest_Serialize }) & { calibration_session?: never; data_source?: never; inventory_session?: never; plan?: never; prepared_source?: never; project?: never; projection?: never };

export type TransitionResponse = TransitionResponse_Serialize | TransitionResponse_Deserialize;

export type TransitionResponse_Deserialize = {
	status: TransitionStatus,
	contractVersion: string,
	requestId: string,
	appliedAt: string | null,
	priorState: string | null,
	newState: string | null,
	auditId: string | null,
	planId: string | null,
	error: TransitionError_Deserialize | null,
};

export type TransitionResponse_Serialize = {
	status: TransitionStatus,
	contractVersion: string,
	requestId: string,
	appliedAt?: string | null,
	priorState?: string | null,
	newState?: string | null,
	auditId?: string | null,
	planId?: string | null,
	error?: TransitionError_Serialize | null,
};

export type TransitionStatus = "success" | "noop" | "error";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

