// Copyright (C) 2024-2026 Sjors Robroek
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * Compatibility barrel for frontend types.
 *
 * Every struct-like type here is a re-export of the generated Specta binding
 * (the camelCase `_Serialize` projection or the plain generated type). There is
 * no hand-written struct universe anymore — the generated bindings are the
 * single source of truth for shape and field naming (spec 042 SC-002 / T268).
 *
 * Genuinely frontend-only types (no backend DTO / not generated by Specta) live
 * in `@/types/frontend` and are re-exported at the bottom of this file so that
 * existing `@/bindings/types` import sites keep working.
 */

// ─── Enum / String-Union Re-exports ─────────────────────────────────────────

// Spec 041 FR-051 (T076, Phase 13): `SessionState` was removed — sessions
// are derived, already-confirmed inventory with no review-state machine.
export type {
  ProjectState,
  ConfidenceLevel,
  ProvenanceOrigin,
  ViewMode,
  Density,
  CalibrationKind,
  PlanItemAction,
  PlanItemState,
  PlanItemProtection,
  PlanOrigin,
  PlanType,
  DestructiveDestination,
  AuditOutcome,
  ReviewItemKind,
  SearchResultKind,
  RootCategory,
  // Spec 041: per-source organization state (move vs catalogue).
  OrganizationState,
  // Spec 008: project source role + selection (canonical in projects_v2.rs)
  SourceRole,
  SourceSelection,
  // SourceViewStrategy — moved to spec 026 (generated source views); remove this
  //   re-export when spec 026 registers its command and emits the type.
  // OutputVerification  — moved to spec 012 (artifact verification); same.
  // CleanupEligibility  — moved to spec 017 cleanup planner; same.
  SessionsGroupBy,
  SessionsView,
  TransitionActor,
  TransitionStatus,
  AuditActor,
  AssetType,
  // Plan response types
  PlanApproveResponse,
  PlanDiscardResponse,
  PlanRetryResponse,
  ArchiveSendToTrashResponse,
  ArchivePermanentlyDeleteResponse,
} from './index';

/**
 * PlanState — re-export from generated bindings. Includes `"paused"` (spec 017
 * data-model.md §PlanState, R-Pause-1) now that it is surfaced in the Rust
 * contracts `PlanState` enum.
 */
export type PlanState = import('./index').PlanState;

// ─── Struct Re-exports (generated _Serialize / plain bindings) ───────────────
//
// Each type below re-exports its generated Specta binding. Consumers and the
// generated bindings share one structural (camelCase) type — there are no
// hand-written struct duplicates (spec 042 SC-002).

/** Re-export generated type so callers continue to import from '@/bindings/types'. */
export type MetaValue = import('./index').MetaValue_Serialize;

/** Re-export generated type (already camelCase). */
export type AppPreferences = import('./index').AppPreferences;

/** Re-export generated type (`{ scope, values }`). */
export type SettingsData = import('./index').SettingsData;

// ─── Entity Re-exports ──────────────────────────────────────────────────────

/** Re-export generated type so callers continue to import from '@/bindings/types'. */
export type AcquisitionSession = import('./index').AcquisitionSession_Serialize;

/** Re-export generated type so callers continue to import from '@/bindings/types'. */
export type CalibrationMaster = import('./index').CalibrationMaster_Serialize;

/** Re-export gen-3 list-item type so callers continue to import from '@/bindings/types'. */
export type Target = import('./index').TargetListItem_Serialize;

/** Re-export generated summary DTO so callers continue to import from '@/bindings/types'. */
export type Project = import('./index').ProjectSummaryDto_Serialize;

/**
 * PlanItem — re-export generated DTO.
 * Matches the Rust `PlanItemDetail` contract DTO (spec 017).
 */
export type PlanItem = import('./index').PlanItemDetail_Serialize;

/**
 * FilesystemPlan — re-export generated summary DTO.
 * Matches the Rust `PlanSummary` contract DTO (spec 017).
 */
export type FilesystemPlan = import('./index').PlanSummary_Serialize;

/** Re-export generated type so callers continue to import from '@/bindings/types'. */
export type AuditEntry = import('./index').AuditEntry_Serialize;

/** Re-export generated type so callers continue to import from '@/bindings/types'. */
export type ReviewItem = import('./index').ReviewItem_Serialize;

/** Re-export generated type so callers continue to import from '@/bindings/types'. */
export type SearchResult = import('./index').SearchResult_Serialize;

/** Re-export generated type so callers continue to import from '@/bindings/types'. */
export type LibraryRoot = import('./index').LibraryRoot_Serialize;

/** Re-export generated type so callers continue to import from '@/bindings/types'. */
export type Equipment = import('./index').Equipment;

// ─── Extended Detail Types ──────────────────────────────────────────────────

/** Re-export generated type so callers continue to import from '@/bindings/types'. */
export type SessionDetail = import('./index').SessionDetail_Serialize;

/** Re-export generated type so callers continue to import from '@/bindings/types'. */
export type MasterDetail = import('./index').MasterDetail_Serialize;

/** Re-export gen-3 detail type so callers continue to import from '@/bindings/types'. */
export type TargetDetail = import('./index').TargetDetailV3_Serialize;

/** Re-export generated type so callers continue to import from '@/bindings/types'. */
export type ProjectDetail = import('./index').ProjectDetailDto_Serialize;

/**
 * PlanDetail — re-export generated DTO.
 * Matches the Rust `PlanDetail` contract DTO (spec 017).
 */
export type PlanDetail = import('./index').PlanDetail_Serialize;

/** Re-export generated type so callers continue to import from '@/bindings/types'. */
export type CalendarData = import('./index').CalendarData;

/** Re-export generated type so callers continue to import from '@/bindings/types'. */
export type RemapVerification = import('./index').RemapVerification;

/** Re-export generated type so callers continue to import from '@/bindings/types'. */
export type MatchCandidate = import('./index').MatchCandidate_Serialize;

// ─── Types NOT in generated bindings (frontend-only) ────────────────────────

export type OperationHandle = import('./index').IpcOperationHandle;

// Long-operation contract event (spec 042 US16, T240). Streamed live over a
// `Channel<OperationEvent>` from the plan-apply command. Re-exported from the
// generated bindings so feature code imports it through the friendly facade.
export type OperationEvent = import('./index').OperationEvent;
export type OperationEventType = import('./index').OperationEventType;

// Frontend-only types (no backend DTO / not generated by Specta) live in
// `@/types/frontend`; re-exported here so existing `@/bindings/types` import
// sites keep working (spec 042 T268).
export type {
  SourceMap,
  ProjectSource,
  ProjectSourceView,
  ProjectOutput,
  ProjectArtifactGroup,
  ProgressEvent,
} from '@/types/frontend';

// Catalog distribution types (spec 014) were removed: target resolution now uses
// the SIMBAD on-demand resolver + bundled seed + local cache (spec 035). The
// hosted/downloaded signed-catalog backend commands no longer exist.
