/**
 * Compatibility barrel for frontend types.
 *
 * Enum / string-union types are re-exported directly from the generated Specta
 * bindings (no field-naming issue).
 *
 * Struct-like types are defined here with **snake_case** field names to match
 * the existing frontend fixtures, mocks, and component code.  When the real
 * Tauri backend is wired (returning camelCase payloads), a follow-up task will
 * migrate all field accesses and switch these to re-exports of the generated
 * `_Serialize` variants.
 *
 * Types that only exist on the frontend side (not generated by Specta) are
 * defined at the bottom of this file.
 */

// ─── Enum / String-Union Re-exports ─────────────────────────────────────────

export type {
  SessionState,
  ProjectState,
  ConfidenceLevel,
  ProvenanceOrigin,
  ViewMode,
  Density,
  CalibrationKind,
  PlanItemAction,
  PlanItemState,
  PlanItemProtection,
  PlanOrigin,
  PlanType,
  DestructiveDestination,
  AuditOutcome,
  ReviewItemKind,
  SearchResultKind,
  TargetKind,
  RootCategory,
  // Spec 008: project source role + selection (canonical in projects_v2.rs)
  SourceRole,
  SourceSelection,
  // SourceViewStrategy — moved to spec 026 (generated source views); remove this
  //   re-export when spec 026 registers its command and emits the type.
  // OutputVerification  — moved to spec 012 (artifact verification); same.
  // CleanupEligibility  — moved to spec 017 cleanup planner; same.
  SessionsGroupBy,
  SessionsView,
  TransitionActor,
  TransitionStatus,
  AuditActor,
  AssetType,
  // Plan response types
  PlanApproveResponse,
  PlanDiscardResponse,
  PlanRetryResponse,
  ArchiveSendToTrashResponse,
  ArchivePermanentlyDeleteResponse,
} from './index';

/**
 * PlanState — re-export from generated bindings. Includes `"paused"` (spec 017
 * data-model.md §PlanState, R-Pause-1) now that it is surfaced in the Rust
 * contracts `PlanState` enum.
 */
export type PlanState = import('./index').PlanState;

// ─── Struct Interfaces (snake_case — matches current frontend convention) ───

export interface MetaValue {
  value: unknown;
  raw?: string;
  origin: import('./index').ProvenanceOrigin;
  confidence: import('./index').ConfidenceLevel;
  evidence_ref?: string;
}

export interface AppPreferences {
  sidebarCollapsed: boolean;
  density: import('./index').Density;
  projectViewModes: Record<string, import('./index').ViewMode>;
  defaultProjectView: import('./index').ViewMode;
  sessionsGroupBy: 'none' | 'target' | 'month' | 'filter' | 'train';
  sessionsView: 'list' | 'calendar';
  tourCompleted: { step1: boolean; step2: boolean; step3: boolean };
  setupCompleted: boolean;
  /** Default scan depth applied to newly added source folders (first-run config). */
  defaultScanDepth: 'recursive' | 'single';
}

export interface SourceMap {
  lights: string[];
  darks: string[];
  flats: string[];
  bias: string[];
  dark_flats: string[];
}

export interface SettingsData {
  [key: string]: unknown;
}

// ─── Entity Interfaces ──────────────────────────────────────────────────────

export interface AcquisitionSession {
  id: string;
  session_key: {
    target: string;
    filter: string;
    binning: string | number;
    gain: string | number;
    night: string;
  };
  state: import('./index').SessionState;
  confidence: import('./index').ConfidenceLevel;
  optical_train_id: string;
  frame_count: number;
  total_integration_seconds: number;
  total_size_bytes: number;
  metadata: Record<string, MetaValue>;
  target_ids: string[];
  project_ids: string[];
  warnings: string[];
}

export interface CalibrationMaster {
  id: string;
  kind: import('./index').CalibrationKind;
  fingerprint: {
    camera: string;
    sensor_mode?: string;
    exposure_s: number;
    temp_c?: number;
    gain: number;
    binning: string;
    filter?: string;
  };
  source_session_id: string;
  created_at: string;
  age_days: number;
  size_bytes: number;
  used_by_session_ids: string[];
  used_by_project_ids: string[];
}

export interface Target {
  id: string;
  name: string;
  aliases: string[];
  catalog_ids: { ngc?: string; ic?: string; messier?: string };
  kind: import('./index').TargetKind;
  coordinates?: { ra?: number; dec?: number };
  session_count: number;
  project_count: number;
  total_integration_hours: number;
  coverage: Record<string, number>;
  recommended_hours: Record<string, number>;
}

export interface Project {
  id: string;
  name: string;
  workflow_profile_id: string;
  root_path: string;
  state: import('./index').ProjectState;
  blocked_reason?: string;
  verification_state: 'unreviewed' | 'has_accepted' | 'all_rejected';
  cleanup_state: { reclaimable_bytes: number };
  integration_hours: number;
  target_ids: string[];
  source_map: SourceMap;
  source_view_ids: string[];
  output_ids: string[];
  processing_directory: string;
  output_directory: string;
  updated_at: string;
}

/**
 * PlanItem — one proposed filesystem operation within a plan.
 * Matches the Rust `PlanItemDetail` contract DTO (spec 017).
 */
export interface PlanItem {
  id: string;
  index: number;
  name: string;
  action: import('./index').PlanItemAction;
  from: string;
  to: string;
  reason: string;
  protection: import('./index').PlanItemProtection;
  linked?: string;
  state: import('./index').PlanItemState;
  failure_reason?: string;
  provenance?: Array<{ label: string; value: string }>;
  approved_mtime?: string;
  approved_size_bytes?: number;
  archive_path?: string;
}

/**
 * FilesystemPlan — plan summary row for the list view.
 * Matches the Rust `PlanSummary` contract DTO (spec 017).
 */
export interface FilesystemPlan {
  id: string;
  number: number;
  title: string;
  origin: import('./index').PlanOrigin;
  origin_path?: string;
  state: PlanState;
  planType: import('./index').PlanType;
  destructiveDestination: import('./index').DestructiveDestination;
  parent_plan_id?: string;
  items_total: number;
  items_applied: number;
  items_failed: number;
  items_skipped: number;
  items_cancelled: number;
  items_pending: number;
  total_bytes_required: number;
  created_at: string;
  approved_at?: string;
  discarded_at?: string;
}

export interface AuditEntry {
  id: string;
  timestamp: string;
  event_type: string;
  entity_type: string;
  entity_id: string;
  from_state?: string;
  to_state?: string;
  actor: 'user' | 'system';
  outcome: import('./index').AuditOutcome;
  detail: string;
}

export interface ReviewItem {
  id: string;
  kind: import('./index').ReviewItemKind;
  session_id?: string;
  file_path?: string;
  confidence: import('./index').ConfidenceLevel;
  blocking_reasons: string[];
  evidence: Record<string, MetaValue>;
  suggested_target?: string;
  suggested_filter?: string;
}

export interface SearchResult {
  id: string;
  kind: import('./index').SearchResultKind;
  label: string;
  sublabel?: string;
  route: string;
  score: number;
}

export interface LibraryRoot {
  id: string;
  path: string;
  category: 'raw' | 'calibration' | 'project' | 'inbox';
  online: boolean;
  file_count: number;
  last_scanned?: string;
}

export interface Equipment {
  id: string;
  name: string;
  kind: string;
  aliases: string[];
}

// ─── Extended Detail Types ──────────────────────────────────────────────────

export interface SessionDetail extends AcquisitionSession {
  framesets: Array<{
    filter: string;
    count: number;
    integration_s: number;
  }>;
  calibration_matches: Array<{
    master_id: string;
    kind: import('./index').CalibrationKind;
    score: number;
    soft_mismatches: string[];
  }>;
  history: Array<{
    timestamp: string;
    event: string;
    actor: string;
  }>;
}

export interface MasterDetail extends CalibrationMaster {
  compatible_sessions: Array<{
    session_id: string;
    score: number;
    soft_mismatches: string[];
  }>;
  usage_stats: { session_count: number; project_count: number };
}

export interface TargetDetail extends Target {
  sessions: AcquisitionSession[];
  projects: Array<{
    id: string;
    name: string;
    state: import('./index').ProjectState;
  }>;
}

export interface ProjectSource {
  role: 'light' | 'dark' | 'flat' | 'bias';
  name: string;
  frames: number;
  hours: string;
  selection: 'selected' | 'candidate';
  warning?: string;
}

export interface ProjectSourceView {
  name: string;
  strategy: 'junction' | 'symlink' | 'hardlink' | 'copy';
  link_count: number;
  plan_ref: string;
}

export interface ProjectOutput {
  id: string;
  filename: string;
  kind: string;
  size_bytes: number;
  date: string;
  verification: 'accepted' | 'unreviewed' | 'superseded';
  protected: boolean;
}

export interface ProjectArtifactGroup {
  type: string;
  count: number;
  total_size_bytes: number;
  cleanup_eligibility: 'eligible' | 'archive' | 'keep' | 'none';
  confidence: import('./index').ConfidenceLevel;
  tool: string;
  protected: boolean;
  warning?: string;
}

export interface ProjectDetail extends Project {
  targets: string[];
  sources: ProjectSource[];
  source_views: ProjectSourceView[];
  outputs: ProjectOutput[];
  artifacts: ProjectArtifactGroup[];
  lifecycle_stage_index: number;
  audit_count: number;
  plan_count: number;
  cleanup_bytes: number;
  cleanup_label: string;
  total_integration_label: string;
  on_disk_label: string;
  notes_count: number;
  manifest_count: number;
}

/**
 * PlanDetail — full plan detail with items for the review/detail view.
 * Matches the Rust `PlanDetail` contract DTO (spec 017).
 */
export interface PlanDetail extends FilesystemPlan {
  approved_at?: string;
  items: PlanItem[];
}

export interface CalendarData {
  months: Array<{
    year: number;
    month: number;
    days: Array<{
      day: number;
      sessions: Array<{ id: string; target: string; filter: string }>;
    }>;
  }>;
}

export interface RemapVerification {
  root_id: string;
  original_path: string;
  new_path: string;
  samples: Array<{ relative_path: string; found: boolean }>;
  all_verified: boolean;
}

export interface MatchCandidate {
  master_id: string;
  kind: import('./index').CalibrationKind;
  score: number;
  filter?: string;
  soft_mismatches: string[];
}

// ─── Types NOT in generated bindings (frontend-only) ────────────────────────

export interface OperationHandle {
  operation_id: string;
  kind: string;
}

export interface ProgressEvent {
  operation_id: string;
  discovered: number;
  total: number;
  current_item: string;
  elapsed_ms: number;
  warnings: string[];
  completion_state?: 'completed' | 'failed' | 'paused';
}

// Catalog distribution types (spec 014) were removed: target resolution now uses
// the SIMBAD on-demand resolver + bundled seed + local cache (spec 035). The
// hosted/downloaded signed-catalog backend commands no longer exist.
