#!/usr/bin/env bash
# DB boundary ratchet — keystone guard for the persistence-layer hardening effort.
#
# Goal: all production SQL must live inside `crates/persistence/db`. This script
# counts raw sqlx query/exec sites in PRODUCTION Rust code OUTSIDE that crate and
# fails if any file EXCEEDS its checked-in baseline. Counts may only shrink (the
# ratchet); brand-new files default to a baseline of 0, so any new leak fails CI.
#
# Why a script and not clippy `disallowed-methods`: clippy cannot path-scope a
# lint to "everywhere except crates/persistence/db". clippy.toml here provides a
# coarse secondary signal only; this ratchet is the real boundary enforcement.
#
# "Production" = `*.rs` files, excluding:
#   - crates/persistence/db/**         (the sanctioned home for SQL)
#   - any path containing a `tests/` segment (integration tests)
#   - the example reference module (query_builder_example.rs)
#   - query sites that appear at/after the first `#[cfg(test)]` line in a file
#     (inline unit-test modules are not production code)
#
# Usage:
#   scripts/check-db-boundary.sh            # check against baseline (CI mode)
#   scripts/check-db-boundary.sh --generate # (re)write the baseline file
#   scripts/check-db-boundary.sh --list     # print current per-file counts
#
# NOTE: regenerate the baseline (`--generate`) after spec 041 merges — its
# inbox/sessions/confirm rewrite changes these counts. The baseline is a
# snapshot of today's leakage, not a target.

set -euo pipefail

# Repo root = parent of this script's directory.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BASELINE="$SCRIPT_DIR/db-boundary-baseline.txt"

# Patterns that denote a raw sqlx query/exec site.
PATTERN='sqlx::query|query_as|query_scalar|\.fetch_(one|all|optional)|\.execute\('

# Count production query sites in a single file (sites before first #[cfg(test)]).
count_file() {
  local file="$1"
  local cutoff
  # Line number of the first #[cfg(test)] (inline unit-test module marker).
  cutoff="$(grep -nE '#\[cfg\(test\)\]' "$file" | head -1 | cut -d: -f1 || true)"
  if [[ -n "$cutoff" ]]; then
    # Production region is everything strictly before the cfg(test) marker.
    head -n "$((cutoff - 1))" "$file" | grep -cE "$PATTERN" || true
  else
    grep -cE "$PATTERN" "$file" || true
  fi
}

# Enumerate candidate production files (sorted, repo-relative paths).
list_files() {
  cd "$ROOT"
  # Search source roots; prune persistence/db and any tests/ directory.
  find crates apps -type f -name '*.rs' \
    -not -path 'crates/persistence/db/*' \
    -not -path '*/tests/*' \
    -not -name 'query_builder_example.rs' \
    | sort
}

# Emit "count<TAB>path" for every file that has >=1 production query site.
collect() {
  local f n
  while IFS= read -r f; do
    n="$(count_file "$ROOT/$f")"
    if [[ "$n" -gt 0 ]]; then
      printf '%d\t%s\n' "$n" "$f"
    fi
  done < <(list_files)
}

case "${1:-}" in
  --generate)
    {
      echo "# DB boundary baseline — production sqlx query/exec sites OUTSIDE crates/persistence/db."
      echo "# Format: <count><TAB><repo-relative path>. Generated by scripts/check-db-boundary.sh --generate."
      echo "# Ratchet rule: a file may only DECREASE its count; new files default to 0."
      echo "# REGENERATE after spec 041 merges (inbox/sessions/confirm rewrite changes counts)."
      collect
    } > "$BASELINE"
    total="$(collect | awk -F'\t' '{s+=$1} END{print s+0}')"
    files="$(collect | wc -l | tr -d ' ')"
    echo "Wrote baseline: $BASELINE"
    echo "  files: $files   total production query sites: $total"
    ;;

  --list)
    collect
    ;;

  ""|--check)
    if [[ ! -f "$BASELINE" ]]; then
      echo "ERROR: baseline missing: $BASELINE" >&2
      echo "Run: scripts/check-db-boundary.sh --generate" >&2
      exit 2
    fi

    # Load baseline into an associative array: path -> allowed count.
    declare -A allowed
    while IFS=$'\t' read -r cnt path; do
      [[ "$cnt" =~ ^#|^$ ]] && continue
      [[ -z "${path:-}" ]] && continue
      allowed["$path"]="$cnt"
    done < <(grep -vE '^[[:space:]]*#' "$BASELINE" | grep -vE '^[[:space:]]*$')

    fail=0
    while IFS=$'\t' read -r cnt path; do
      base="${allowed[$path]:-0}"
      if [[ "$cnt" -gt "$base" ]]; then
        echo "BOUNDARY REGRESSION: $path has $cnt production query site(s), baseline allows $base" >&2
        fail=1
      fi
    done < <(collect)

    if [[ "$fail" -ne 0 ]]; then
      echo "" >&2
      echo "DB boundary ratchet failed: new/raw SQL appeared outside crates/persistence/db." >&2
      echo "Move the query into a persistence/db repository, or (if intentional and reviewed)" >&2
      echo "regenerate the baseline with: scripts/check-db-boundary.sh --generate" >&2
      exit 1
    fi

    total="$(collect | awk -F'\t' '{s+=$1} END{print s+0}')"
    files="$(collect | wc -l | tr -d ' ')"
    echo "DB boundary OK — $files file(s), $total production query site(s) within baseline."
    ;;

  *)
    echo "usage: $0 [--check|--generate|--list]" >&2
    exit 2
    ;;
esac
