// AUTO-GENERATED by scripts/gen-panda-tokens.mjs from apps/desktop/tokens/
// Do not edit by hand. Run `node apps/desktop/scripts/gen-panda-tokens.mjs`
// after editing the DTCG sources. CI fails if this file drifts.

export const conditions = {
  "espressoDark": "[data-theme=\"espresso-dark\"] &",
  "observatoryCool": "[data-theme=\"observatory-cool\"] &",
  "observatoryCoolLight": "[data-theme=\"observatory-cool-light\"] &",
  "observatoryDark": "[data-theme=\"observatory-dark\"] &",
  "warmClay": "[data-theme=\"warm-clay\"] &",
  "warmSlate": ":root:not([data-theme]) &, [data-theme=\"warm-slate\"] &"
};

export const foundationTokens = {
  "font-sans": {
    "value": "'Inter', system-ui, -apple-system, sans-serif"
  },
  "font-display": {
    "value": "'Space Grotesk Variable', 'Inter Variable', system-ui, sans-serif"
  },
  "text-xs": {
    "value": "0.7857rem"
  },
  "text-sm": {
    "value": "0.8571rem"
  },
  "text-base": {
    "value": "1rem"
  },
  "text-md": {
    "value": "1.1429rem"
  },
  "text-lg": {
    "value": "1.2857rem"
  },
  "text-xl": {
    "value": "1.4286rem"
  },
  "text-2xl": {
    "value": "1.7143rem"
  },
  "tracking-tight": {
    "value": "0.03em"
  },
  "tracking-normal": {
    "value": "0.04em"
  },
  "tracking-wide": {
    "value": "0.08em"
  },
  "weight-normal": {
    "value": "400"
  },
  "weight-medium": {
    "value": "500"
  },
  "weight-semibold": {
    "value": "600"
  },
  "leading-tight": {
    "value": "1.2"
  },
  "leading-normal": {
    "value": "1.5"
  },
  "leading-relaxed": {
    "value": "1.6"
  },
  "sp-0": {
    "value": "2px"
  },
  "sp-1": {
    "value": "4px"
  },
  "sp-2": {
    "value": "8px"
  },
  "sp-3": {
    "value": "12px"
  },
  "sp-4": {
    "value": "16px"
  },
  "sp-5": {
    "value": "24px"
  },
  "sp-6": {
    "value": "32px"
  },
  "sp-7": {
    "value": "48px"
  },
  "transition-fast": {
    "value": "100ms ease"
  },
  "transition-base": {
    "value": "150ms ease"
  },
  "transition-slow": {
    "value": "250ms ease"
  },
  "radius-sm": {
    "value": "3px"
  },
  "radius-md": {
    "value": "5px"
  },
  "radius-lg": {
    "value": "8px"
  }
};

export const semanticTokens = {
  "accent": {
    "value": {
      "_espressoDark": "#cf9d63",
      "_observatoryCool": "#3fb2c2",
      "_observatoryCoolLight": "#276f7c",
      "_observatoryDark": "#d98a3d",
      "_warmClay": "#b25a35",
      "_warmSlate": "#3f6b7a",
      "base": "#3f6b7a"
    }
  },
  "accent-bg": {
    "value": {
      "_espressoDark": "#312517",
      "_observatoryCool": "#16303a",
      "_observatoryCoolLight": "#dbebef",
      "_observatoryDark": "#3a2c1b",
      "_warmClay": "#f3e3d8",
      "_warmSlate": "#e3edf0",
      "base": "#e3edf0"
    }
  },
  "accent-deep": {
    "value": {
      "_espressoDark": "#b8843f",
      "_observatoryCool": "#2c8592",
      "_observatoryCoolLight": "#1a4a53",
      "_observatoryDark": "#b86f2a",
      "_warmClay": "#7c3a1f",
      "_warmSlate": "#2a4651",
      "base": "#2a4651"
    }
  },
  "accent-hover": {
    "value": {
      "_espressoDark": "#ddac72",
      "_observatoryCool": "#54c3d1",
      "_observatoryCoolLight": "#215d68",
      "_observatoryDark": "#e89a4d",
      "_warmClay": "#9c4c2a",
      "_warmSlate": "#345863",
      "base": "#345863"
    }
  },
  "accent-text": {
    "value": {
      "_espressoDark": "#d9ad77",
      "_observatoryCool": "#66cedb",
      "_observatoryCoolLight": "#1c6470",
      "_observatoryDark": "#e8a86a",
      "_warmClay": "#8a4324",
      "_warmSlate": "#2c5160",
      "base": "#2c5160"
    }
  },
  "bg": {
    "value": {
      "_espressoDark": "#161412",
      "_observatoryCool": "#12151b",
      "_observatoryCoolLight": "#f2f4f8",
      "_observatoryDark": "#1b1916",
      "_warmClay": "#f6f4ef",
      "_warmSlate": "#f5f4f1",
      "base": "#f5f4f1"
    }
  },
  "bg3": {
    "value": {
      "_espressoDark": "#272320",
      "_observatoryCool": "#212734",
      "_observatoryCoolLight": "#dde3eb",
      "_observatoryDark": "#2c281f",
      "_warmClay": "#e6e0d4",
      "_warmSlate": "#e2e0d9",
      "base": "#e2e0d9"
    }
  },
  "control-border": {
    "value": {
      "_espressoDark": "#726f6a",
      "_observatoryCool": "#6f7379",
      "_observatoryCoolLight": "#7b7f86",
      "_observatoryDark": "#76736b",
      "_warmClay": "#817d77",
      "_warmSlate": "#7d7d7a",
      "base": "#7d7d7a"
    }
  },
  "danger": {
    "value": {
      "_espressoDark": "#e0907c",
      "_observatoryCool": "#e08a76",
      "_observatoryCoolLight": "#8a2a1a",
      "_observatoryDark": "#e08a76",
      "_warmClay": "#8a2a1a",
      "_warmSlate": "#8a2a1a",
      "base": "#8a2a1a"
    }
  },
  "danger-bg": {
    "value": {
      "_espressoDark": "#2c1a16",
      "_observatoryCool": "#2b1a16",
      "_observatoryCoolLight": "#f2e0db",
      "_observatoryDark": "#2e1c18",
      "_warmClay": "#f3e0db",
      "_warmSlate": "#f3e0db",
      "base": "#f3e0db"
    }
  },
  "danger-bg-hover": {
    "value": {
      "_espressoDark": "#38221c",
      "_observatoryCool": "#38221c",
      "_observatoryCoolLight": "#ebcfc6",
      "_observatoryDark": "#3a241e",
      "_warmClay": "#ecccc2",
      "_warmSlate": "#eccfc6",
      "base": "#eccfc6"
    }
  },
  "danger-border": {
    "value": {
      "_espressoDark": "#4d2d25",
      "_observatoryCool": "#4d2d25",
      "_observatoryCoolLight": "#dfbdb3",
      "_observatoryDark": "#502f27",
      "_warmClay": "#e0bdb3",
      "_warmSlate": "#e0bdb3",
      "base": "#e0bdb3"
    }
  },
  "destructive": {
    "value": {
      "_espressoDark": "#f24b3a",
      "_observatoryCool": "#f24b3a",
      "_observatoryCoolLight": "#c0392b",
      "_observatoryDark": "#f24b3a",
      "_warmClay": "#951c14",
      "_warmSlate": "#c0392b",
      "base": "#c0392b"
    }
  },
  "destructive-bg": {
    "value": {
      "_espressoDark": "#2a1613",
      "_observatoryCool": "#2a1613",
      "_observatoryCoolLight": "#f7e4e0",
      "_observatoryDark": "#2a1613",
      "_warmClay": "#f7e4e0",
      "_warmSlate": "#f7e4e0",
      "base": "#f7e4e0"
    }
  },
  "destructive-bg-hover": {
    "value": {
      "_espressoDark": "#371a15",
      "_observatoryCool": "#371a15",
      "_observatoryCoolLight": "#f0cfc9",
      "_observatoryDark": "#371a15",
      "_warmClay": "#f0cfc9",
      "_warmSlate": "#f0cfc9",
      "base": "#f0cfc9"
    }
  },
  "hover-bg": {
    "value": {
      "_espressoDark": "rgba(255,255,255,0.05)",
      "_observatoryCool": "rgba(255,255,255,0.05)",
      "_observatoryCoolLight": "rgba(0,0,0,0.04)",
      "_observatoryDark": "rgba(255,255,255,0.05)",
      "_warmClay": "rgba(0,0,0,0.04)",
      "_warmSlate": "rgba(0,0,0,0.04)",
      "base": "rgba(0,0,0,0.04)"
    }
  },
  "info": {
    "value": {
      "_espressoDark": "#86b3cc",
      "_observatoryCool": "#86b3cc",
      "_observatoryCoolLight": "#35566a",
      "_observatoryDark": "#86b3cc",
      "_warmClay": "#3a5566",
      "_warmSlate": "#3a5566",
      "base": "#3a5566"
    }
  },
  "info-bg": {
    "value": {
      "_espressoDark": "#18242e",
      "_observatoryCool": "#152331",
      "_observatoryCoolLight": "#e5eef2",
      "_observatoryDark": "#1a2630",
      "_warmClay": "#e8eef1",
      "_warmSlate": "#e8eef1",
      "base": "#e8eef1"
    }
  },
  "info-border": {
    "value": {
      "_espressoDark": "#314556",
      "_observatoryCool": "#2f4658",
      "_observatoryCoolLight": "#bcd2dc",
      "_observatoryDark": "#33485a",
      "_warmClay": "#bcd0db",
      "_warmSlate": "#bcd0db",
      "base": "#bcd0db"
    }
  },
  "ink": {
    "value": {
      "_espressoDark": "#ece7df",
      "_observatoryCool": "#eef2f7",
      "_observatoryCoolLight": "#191d24",
      "_observatoryDark": "#f0ebe2",
      "_warmClay": "#221f1a",
      "_warmSlate": "#20211f",
      "base": "#20211f"
    }
  },
  "ink2": {
    "value": {
      "_espressoDark": "#cabfae",
      "_observatoryCool": "#c5cdd8",
      "_observatoryCoolLight": "#3a414b",
      "_observatoryDark": "#cfc7b8",
      "_warmClay": "#433e35",
      "_warmSlate": "#42433f",
      "base": "#42433f"
    }
  },
  "ink3": {
    "value": {
      "_espressoDark": "#9b9384",
      "_observatoryCool": "#98a2b0",
      "_observatoryCoolLight": "#565e6a",
      "_observatoryDark": "#a59c8a",
      "_warmClay": "#5b544a",
      "_warmSlate": "#5a5b54",
      "base": "#5a5b54"
    }
  },
  "ink4": {
    "value": {
      "_espressoDark": "#9c947f",
      "_observatoryCool": "#8592a1",
      "_observatoryCoolLight": "#525a66",
      "_observatoryDark": "#9a9180",
      "_warmClay": "#625b50",
      "_warmSlate": "#606159",
      "base": "#606159"
    }
  },
  "input-recessed-bg": {
    "value": {
      "_espressoDark": "#1e1b18",
      "_observatoryCool": "#191d25",
      "_observatoryCoolLight": "#f2f4f8",
      "_observatoryDark": "#232019",
      "_warmClay": "#f6f4ef",
      "_warmSlate": "#f5f4f1",
      "base": "#f5f4f1"
    }
  },
  "ok": {
    "value": {
      "_espressoDark": "#86b98f",
      "_observatoryCool": "#6fc191",
      "_observatoryCoolLight": "#3a6b48",
      "_observatoryDark": "#7fb88a",
      "_warmClay": "#3a6b48",
      "_warmSlate": "#3a6b48",
      "base": "#3a6b48"
    }
  },
  "ok-bg": {
    "value": {
      "_espressoDark": "#1d2620",
      "_observatoryCool": "#16261d",
      "_observatoryCoolLight": "#e6efe8",
      "_observatoryDark": "#1f2a20",
      "_warmClay": "#e9f0e6",
      "_warmSlate": "#e7efe6",
      "base": "#e7efe6"
    }
  },
  "ok-border": {
    "value": {
      "_espressoDark": "#36473a",
      "_observatoryCool": "#2f4638",
      "_observatoryCoolLight": "#bcd0bf",
      "_observatoryDark": "#3a4d3c",
      "_warmClay": "#c2d3b8",
      "_warmSlate": "#bcd0b8",
      "base": "#bcd0b8"
    }
  },
  "on-accent": {
    "value": {
      "_espressoDark": "#161412",
      "_observatoryCool": "#0c1014",
      "_observatoryCoolLight": "#ffffff",
      "_observatoryDark": "#1b1916",
      "_warmClay": "#ffffff",
      "_warmSlate": "#ffffff",
      "base": "#ffffff"
    }
  },
  "onb-spotlight-stroke": {
    "value": {
      "_espressoDark": "#cf9d63",
      "_observatoryCool": "#3fb2c2",
      "_observatoryCoolLight": "#ffffff",
      "_observatoryDark": "#d98a3d",
      "_warmClay": "#ffffff",
      "_warmSlate": "#ffffff",
      "base": "#ffffff"
    }
  },
  "rule": {
    "value": {
      "_espressoDark": "#332e28",
      "_observatoryCool": "#303845",
      "_observatoryCoolLight": "#cbd2dd",
      "_observatoryDark": "#3a352b",
      "_warmClay": "#d8d1c4",
      "_warmSlate": "#d5d3cb",
      "base": "#d5d3cb"
    }
  },
  "rule2": {
    "value": {
      "_espressoDark": "#272320",
      "_observatoryCool": "#252c37",
      "_observatoryCoolLight": "#dce1ea",
      "_observatoryDark": "#2e2a22",
      "_warmClay": "#e8e2d6",
      "_warmSlate": "#e6e4dd",
      "base": "#e6e4dd"
    }
  },
  "selected-bg": {
    "value": {
      "_espressoDark": "#2e271d",
      "_observatoryCool": "#1e2733",
      "_observatoryCoolLight": "#e0eaef",
      "_observatoryDark": "#332a1d",
      "_warmClay": "#f1e6da",
      "_warmSlate": "#e6ecee",
      "base": "#e6ecee"
    }
  },
  "shadow-lg": {
    "value": {
      "_espressoDark": "0 8px 24px rgba(0,0,0,0.6)",
      "_observatoryCool": "0 8px 24px rgba(0,0,0,0.55)",
      "_observatoryCoolLight": "0 8px 24px rgba(0,0,0,0.14)",
      "_observatoryDark": "0 8px 24px rgba(0,0,0,0.55)",
      "_warmClay": "0 8px 24px rgba(0,0,0,0.14)",
      "_warmSlate": "0 8px 24px rgba(0,0,0,0.14)",
      "base": "0 8px 24px rgba(0,0,0,0.14)"
    }
  },
  "shadow-sm": {
    "value": {
      "_espressoDark": "0 1px 3px rgba(0,0,0,0.5)",
      "_observatoryCool": "0 1px 3px rgba(0,0,0,0.5)",
      "_observatoryCoolLight": "0 1px 2px rgba(0,0,0,0.08)",
      "_observatoryDark": "0 1px 3px rgba(0,0,0,0.4)",
      "_warmClay": "0 1px 2px rgba(0,0,0,0.08)",
      "_warmSlate": "0 1px 2px rgba(0,0,0,0.08)",
      "base": "0 1px 2px rgba(0,0,0,0.08)"
    }
  },
  "surface": {
    "value": {
      "_espressoDark": "#1e1b18",
      "_observatoryCool": "#191d25",
      "_observatoryCoolLight": "#e8ecf2",
      "_observatoryDark": "#232019",
      "_warmClay": "#efeae1",
      "_warmSlate": "#ecebe6",
      "base": "#ecebe6"
    }
  },
  "surface-raised": {
    "value": {
      "_espressoDark": "#1e1b18",
      "_observatoryCool": "#1c212a",
      "_observatoryCoolLight": "#ffffff",
      "_observatoryDark": "#26221b",
      "_warmClay": "#fffdf9",
      "_warmSlate": "#ffffff",
      "base": "#ffffff"
    }
  },
  "warn": {
    "value": {
      "_espressoDark": "#d6b257",
      "_observatoryCool": "#d8b24e",
      "_observatoryCoolLight": "#7a5a1a",
      "_observatoryDark": "#d8b24e",
      "_warmClay": "#7a5a1a",
      "_warmSlate": "#7a5a1a",
      "base": "#7a5a1a"
    }
  },
  "warn-bg": {
    "value": {
      "_espressoDark": "#282215",
      "_observatoryCool": "#2a2415",
      "_observatoryCoolLight": "#f4edd6",
      "_observatoryDark": "#2c2616",
      "_warmClay": "#f6eed6",
      "_warmSlate": "#f5eed6",
      "base": "#f5eed6"
    }
  },
  "warn-border": {
    "value": {
      "_espressoDark": "#4a3f24",
      "_observatoryCool": "#4a3f24",
      "_observatoryCoolLight": "#ddce9e",
      "_observatoryDark": "#4d4327",
      "_warmClay": "#e0cf9e",
      "_warmSlate": "#e0cf9e",
      "base": "#e0cf9e"
    }
  },
  "text": {
    "value": "{colors.ink}"
  },
  "text-secondary": {
    "value": "{colors.ink2}"
  },
  "text-muted": {
    "value": "{colors.ink3}"
  },
  "text-faint": {
    "value": "{colors.ink4}"
  },
  "border": {
    "value": "{colors.rule}"
  },
  "border-subtle": {
    "value": "{colors.rule2}"
  },
  "chip": {
    "value": "{colors.bg3}"
  },
  "link": {
    "value": "{colors.accent-text}"
  },
  "focus-ring": {
    "value": {
      "_espressoDark": "0 0 0 2px #cf9d63",
      "_observatoryCool": "0 0 0 2px #3fb2c2",
      "_observatoryCoolLight": "0 0 0 2px #276f7c",
      "_observatoryDark": "0 0 0 2px #d98a3d",
      "_warmClay": "0 0 0 2px #b25a35",
      "_warmSlate": "0 0 0 2px #3f6b7a",
      "base": "0 0 0 2px #3f6b7a"
    }
  },
  "font-mono": {
    "value": "ui-monospace, 'Cascadia Code', monospace"
  }
};
