/**
 * Frontend-only types: no backend DTO / not generated by Specta.
 *
 * These shapes exist purely on the frontend (design-V3 fixture/display shapes,
 * legacy progress payloads, and helper maps that the Rust contracts never
 * model). Anything with a generated `_Serialize` equivalent lives in
 * `@/bindings/types` as a re-export instead — see spec 042 T268.
 */

import type { ProvenanceOrigin, ConfidenceLevel } from '@/bindings/index';

/**
 * SourceMap — frame-type → relative-path buckets used by the inbox/source-view
 * fixtures. Not a backend DTO (the Rust side models sources individually).
 */
export interface SourceMap {
  lights: string[];
  darks: string[];
  flats: string[];
  bias: string[];
  dark_flats: string[];
}

/**
 * ProjectSource — design-V3 project-detail fixture row. The generated
 * `ProjectSourceDto_Serialize` has a different (inventory-linked) shape, so
 * this display-only fixture type stays frontend-local.
 */
export interface ProjectSource {
  role: 'light' | 'dark' | 'flat' | 'bias';
  name: string;
  frames: number;
  hours: string;
  selection: 'selected' | 'candidate';
  warning?: string;
}

/**
 * ProjectSourceView — design-V3 generated-view fixture row. No backend DTO
 * (spec 026 prepared-source views use `GeneratedViewRefDto` / `PreparedViewSummary`).
 */
export interface ProjectSourceView {
  name: string;
  strategy: 'junction' | 'symlink' | 'hardlink' | 'copy';
  link_count: number;
  plan_ref: string;
}

/**
 * ProjectOutput — design-V3 project-output fixture row. No backend DTO yet.
 */
export interface ProjectOutput {
  id: string;
  filename: string;
  kind: string;
  size_bytes: number;
  date: string;
  verification: 'accepted' | 'unreviewed' | 'superseded';
  protected: boolean;
}

/**
 * ProjectArtifactGroup — design-V3 cleanup-candidate fixture row. No backend
 * DTO yet (spec 017 cleanup planner emits its own contract types).
 */
export interface ProjectArtifactGroup {
  type: string;
  count: number;
  total_size_bytes: number;
  cleanup_eligibility: 'eligible' | 'archive' | 'keep' | 'none';
  confidence: ConfidenceLevel;
  tool: string;
  protected: boolean;
  warning?: string;
}

/**
 * ProgressEvent — legacy long-operation progress payload. Superseded by the
 * generated `OperationEvent` (spec 042 US16); retained only for any remaining
 * frontend fixture/consumer that predates the channel contract.
 */
export interface ProgressEvent {
  operation_id: string;
  discovered: number;
  total: number;
  current_item: string;
  elapsed_ms: number;
  warnings: string[];
  completion_state?: 'completed' | 'failed' | 'paused';
}

// Re-exported here only so legacy MetaValue fixtures that referenced the
// frontend module's provenance enums keep a single import site.
export type { ProvenanceOrigin, ConfidenceLevel };
